-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fir_filter is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 9;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of fir_filter is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "fir_filter_fir_filter,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.807562,HLS_SYN_LAT=549,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=4748,HLS_SYN_LUT=3572,HLS_VERSION=2024_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv31_20 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000100000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv31_400 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000010000000000";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv11_3FF : STD_LOGIC_VECTOR (10 downto 0) := "01111111111";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv6_2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv6_4 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_const_lv6_5 : STD_LOGIC_VECTOR (5 downto 0) := "000101";
    constant ap_const_lv6_6 : STD_LOGIC_VECTOR (5 downto 0) := "000110";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv6_8 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_const_lv6_9 : STD_LOGIC_VECTOR (5 downto 0) := "001001";
    constant ap_const_lv6_A : STD_LOGIC_VECTOR (5 downto 0) := "001010";
    constant ap_const_lv6_B : STD_LOGIC_VECTOR (5 downto 0) := "001011";
    constant ap_const_lv6_C : STD_LOGIC_VECTOR (5 downto 0) := "001100";
    constant ap_const_lv6_D : STD_LOGIC_VECTOR (5 downto 0) := "001101";
    constant ap_const_lv6_E : STD_LOGIC_VECTOR (5 downto 0) := "001110";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv6_10 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_const_lv6_11 : STD_LOGIC_VECTOR (5 downto 0) := "010001";
    constant ap_const_lv6_12 : STD_LOGIC_VECTOR (5 downto 0) := "010010";
    constant ap_const_lv6_13 : STD_LOGIC_VECTOR (5 downto 0) := "010011";
    constant ap_const_lv6_14 : STD_LOGIC_VECTOR (5 downto 0) := "010100";
    constant ap_const_lv6_15 : STD_LOGIC_VECTOR (5 downto 0) := "010101";
    constant ap_const_lv6_16 : STD_LOGIC_VECTOR (5 downto 0) := "010110";
    constant ap_const_lv6_17 : STD_LOGIC_VECTOR (5 downto 0) := "010111";
    constant ap_const_lv6_18 : STD_LOGIC_VECTOR (5 downto 0) := "011000";
    constant ap_const_lv6_19 : STD_LOGIC_VECTOR (5 downto 0) := "011001";
    constant ap_const_lv6_1A : STD_LOGIC_VECTOR (5 downto 0) := "011010";
    constant ap_const_lv6_1B : STD_LOGIC_VECTOR (5 downto 0) := "011011";
    constant ap_const_lv6_1C : STD_LOGIC_VECTOR (5 downto 0) := "011100";
    constant ap_const_lv6_1D : STD_LOGIC_VECTOR (5 downto 0) := "011101";
    constant ap_const_lv6_1E : STD_LOGIC_VECTOR (5 downto 0) := "011110";
    constant ap_const_lv32_FFFFFBFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111101111111111";
    constant ap_const_lv32_400 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010000000000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal coeffs_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_4 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_5 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_6 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_7 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_8 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_9 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_10 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_11 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_12 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_13 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_14 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_15 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_16 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_17 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_18 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_19 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_20 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_21 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_22 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_23 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_24 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_25 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_26 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_27 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_28 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_29 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_30 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_31 : STD_LOGIC_VECTOR (15 downto 0);
    signal num_taps : STD_LOGIC_VECTOR (31 downto 0);
    signal num_samples : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln7_fu_605_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln7_reg_959 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln33_fu_609_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln33_reg_964 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub50_fu_647_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub50_reg_969 : STD_LOGIC_VECTOR (10 downto 0);
    signal coeffs_0_read_reg_974 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_1_read_reg_979 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_2_read_reg_984 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_3_read_reg_989 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_4_read_reg_994 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_5_read_reg_999 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_6_read_reg_1004 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_7_read_reg_1009 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_8_read_reg_1014 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_9_read_reg_1019 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_10_read_reg_1024 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_11_read_reg_1029 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_12_read_reg_1034 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_13_read_reg_1039 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_14_read_reg_1044 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_15_read_reg_1049 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_16_read_reg_1054 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_17_read_reg_1059 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_18_read_reg_1064 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_19_read_reg_1069 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_20_read_reg_1074 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_21_read_reg_1079 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_22_read_reg_1084 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_23_read_reg_1089 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_24_read_reg_1094 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_25_read_reg_1099 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_26_read_reg_1104 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_27_read_reg_1109 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_28_read_reg_1114 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_29_read_reg_1119 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_30_read_reg_1124 : STD_LOGIC_VECTOR (15 downto 0);
    signal coeffs_31_read_reg_1129 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln44_fu_667_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln44_reg_1134 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_fu_691_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_1140 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal cmp31_2_fu_698_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_2_reg_1145 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp4_fu_715_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp4_reg_1150 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_4_fu_722_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_4_reg_1155 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_5_fu_729_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_5_reg_1160 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_6_fu_736_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_6_reg_1165 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp7_fu_753_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp7_reg_1170 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_8_fu_760_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_8_reg_1175 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_9_fu_767_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_9_reg_1180 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_10_fu_774_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_10_reg_1185 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_11_fu_781_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_11_reg_1190 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_12_fu_788_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_12_reg_1195 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_13_fu_795_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_13_reg_1200 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_14_fu_802_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_14_reg_1205 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp10_fu_819_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp10_reg_1210 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_16_fu_826_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_16_reg_1215 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_17_fu_833_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_17_reg_1220 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_18_fu_840_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_18_reg_1225 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_19_fu_847_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_19_reg_1230 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_20_fu_854_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_20_reg_1235 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_21_fu_861_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_21_reg_1240 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_22_fu_868_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_22_reg_1245 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_23_fu_875_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_23_reg_1250 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_24_fu_882_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_24_reg_1255 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_25_fu_889_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_25_reg_1260 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_26_fu_896_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_26_reg_1265 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_27_fu_903_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_27_reg_1270 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_28_fu_910_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_28_reg_1275 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_29_fu_917_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_29_reg_1280 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_30_fu_924_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp31_30_reg_1285 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_reg_1290 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_1_fu_950_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln44_1_reg_1295 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fir_filter_Pipeline_sample_loop_fu_498_ap_start : STD_LOGIC;
    signal grp_fir_filter_Pipeline_sample_loop_fu_498_ap_done : STD_LOGIC;
    signal grp_fir_filter_Pipeline_sample_loop_fu_498_ap_idle : STD_LOGIC;
    signal grp_fir_filter_Pipeline_sample_loop_fu_498_ap_ready : STD_LOGIC;
    signal grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TREADY : STD_LOGIC;
    signal grp_fir_filter_Pipeline_sample_loop_fu_498_in_stream_TREADY : STD_LOGIC;
    signal grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TVALID : STD_LOGIC;
    signal grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fir_filter_Pipeline_sample_loop_fu_498_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln30_fu_591_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln3_1_fu_587_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln30_fu_597_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_fu_615_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln3_fu_583_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln36_fu_623_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln8_fu_631_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln39_fu_635_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal num_samples_addr_0_op_fu_641_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal empty_fu_655_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_fu_661_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln33_fu_675_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_1_fu_681_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_705_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_743_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_4_fu_809_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_49_fu_940_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_1_fu_945_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal regslice_both_out_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream_TVALID_int_regslice : STD_LOGIC;
    signal in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_ack_in : STD_LOGIC;
    signal out_stream_TVALID_int_regslice : STD_LOGIC;
    signal out_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_stream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fir_filter_fir_filter_Pipeline_sample_loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_stream_TVALID : IN STD_LOGIC;
        out_stream_TREADY : IN STD_LOGIC;
        select_ln44_1 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_stream_TREADY : OUT STD_LOGIC;
        in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_0_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        coeffs_1_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        icmp : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_2_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp31_2 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_3_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        icmp4 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_4_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp31_4 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_5_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp31_5 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_6_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp31_6 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_7_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        icmp7 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_8_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp31_8 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_9_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp31_9 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_10_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp31_10 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_11_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp31_11 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_12_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp31_12 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_13_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp31_13 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_14_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp31_14 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_15_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        icmp10 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_16_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp31_16 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_17_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp31_17 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_18_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp31_18 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_19_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp31_19 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_20_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp31_20 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_21_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp31_21 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_22_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp31_22 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_23_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp31_23 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_24_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp31_24 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_25_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp31_25 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_26_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp31_26 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_27_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp31_27 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_28_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp31_28 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_29_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp31_29 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_30_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp31_30 : IN STD_LOGIC_VECTOR (0 downto 0);
        coeffs_31_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        empty : IN STD_LOGIC_VECTOR (0 downto 0);
        sext_ln44 : IN STD_LOGIC_VECTOR (10 downto 0);
        out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_stream_TVALID : OUT STD_LOGIC;
        out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component fir_filter_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        coeffs_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_15 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_16 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_17 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_18 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_19 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_20 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_21 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_22 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_23 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_24 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_25 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_26 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_27 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_28 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_29 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_30 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_31 : OUT STD_LOGIC_VECTOR (15 downto 0);
        num_taps : OUT STD_LOGIC_VECTOR (31 downto 0);
        num_samples : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component fir_filter_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_fir_filter_Pipeline_sample_loop_fu_498 : component fir_filter_fir_filter_Pipeline_sample_loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_fir_filter_Pipeline_sample_loop_fu_498_ap_start,
        ap_done => grp_fir_filter_Pipeline_sample_loop_fu_498_ap_done,
        ap_idle => grp_fir_filter_Pipeline_sample_loop_fu_498_ap_idle,
        ap_ready => grp_fir_filter_Pipeline_sample_loop_fu_498_ap_ready,
        in_stream_TVALID => in_stream_TVALID_int_regslice,
        out_stream_TREADY => grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TREADY,
        select_ln44_1 => select_ln44_1_reg_1295,
        in_stream_TDATA => in_stream_TDATA_int_regslice,
        in_stream_TREADY => grp_fir_filter_Pipeline_sample_loop_fu_498_in_stream_TREADY,
        in_stream_TKEEP => in_stream_TKEEP_int_regslice,
        in_stream_TSTRB => in_stream_TSTRB_int_regslice,
        in_stream_TLAST => in_stream_TLAST_int_regslice,
        coeffs_0_load_cast => coeffs_0_read_reg_974,
        coeffs_1_load_cast => coeffs_1_read_reg_979,
        icmp => icmp_reg_1140,
        coeffs_2_load_cast => coeffs_2_read_reg_984,
        cmp31_2 => cmp31_2_reg_1145,
        coeffs_3_load_cast => coeffs_3_read_reg_989,
        icmp4 => icmp4_reg_1150,
        coeffs_4_load_cast => coeffs_4_read_reg_994,
        cmp31_4 => cmp31_4_reg_1155,
        coeffs_5_load_cast => coeffs_5_read_reg_999,
        cmp31_5 => cmp31_5_reg_1160,
        coeffs_6_load_cast => coeffs_6_read_reg_1004,
        cmp31_6 => cmp31_6_reg_1165,
        coeffs_7_load_cast => coeffs_7_read_reg_1009,
        icmp7 => icmp7_reg_1170,
        coeffs_8_load_cast => coeffs_8_read_reg_1014,
        cmp31_8 => cmp31_8_reg_1175,
        coeffs_9_load_cast => coeffs_9_read_reg_1019,
        cmp31_9 => cmp31_9_reg_1180,
        coeffs_10_load_cast => coeffs_10_read_reg_1024,
        cmp31_10 => cmp31_10_reg_1185,
        coeffs_11_load_cast => coeffs_11_read_reg_1029,
        cmp31_11 => cmp31_11_reg_1190,
        coeffs_12_load_cast => coeffs_12_read_reg_1034,
        cmp31_12 => cmp31_12_reg_1195,
        coeffs_13_load_cast => coeffs_13_read_reg_1039,
        cmp31_13 => cmp31_13_reg_1200,
        coeffs_14_load_cast => coeffs_14_read_reg_1044,
        cmp31_14 => cmp31_14_reg_1205,
        coeffs_15_load_cast => coeffs_15_read_reg_1049,
        icmp10 => icmp10_reg_1210,
        coeffs_16_load_cast => coeffs_16_read_reg_1054,
        cmp31_16 => cmp31_16_reg_1215,
        coeffs_17_load_cast => coeffs_17_read_reg_1059,
        cmp31_17 => cmp31_17_reg_1220,
        coeffs_18_load_cast => coeffs_18_read_reg_1064,
        cmp31_18 => cmp31_18_reg_1225,
        coeffs_19_load_cast => coeffs_19_read_reg_1069,
        cmp31_19 => cmp31_19_reg_1230,
        coeffs_20_load_cast => coeffs_20_read_reg_1074,
        cmp31_20 => cmp31_20_reg_1235,
        coeffs_21_load_cast => coeffs_21_read_reg_1079,
        cmp31_21 => cmp31_21_reg_1240,
        coeffs_22_load_cast => coeffs_22_read_reg_1084,
        cmp31_22 => cmp31_22_reg_1245,
        coeffs_23_load_cast => coeffs_23_read_reg_1089,
        cmp31_23 => cmp31_23_reg_1250,
        coeffs_24_load_cast => coeffs_24_read_reg_1094,
        cmp31_24 => cmp31_24_reg_1255,
        coeffs_25_load_cast => coeffs_25_read_reg_1099,
        cmp31_25 => cmp31_25_reg_1260,
        coeffs_26_load_cast => coeffs_26_read_reg_1104,
        cmp31_26 => cmp31_26_reg_1265,
        coeffs_27_load_cast => coeffs_27_read_reg_1109,
        cmp31_27 => cmp31_27_reg_1270,
        coeffs_28_load_cast => coeffs_28_read_reg_1114,
        cmp31_28 => cmp31_28_reg_1275,
        coeffs_29_load_cast => coeffs_29_read_reg_1119,
        cmp31_29 => cmp31_29_reg_1280,
        coeffs_30_load_cast => coeffs_30_read_reg_1124,
        cmp31_30 => cmp31_30_reg_1285,
        coeffs_31_load_cast => coeffs_31_read_reg_1129,
        empty => tmp_5_reg_1290,
        sext_ln44 => sub50_reg_969,
        out_stream_TDATA => grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TDATA,
        out_stream_TVALID => grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TVALID,
        out_stream_TKEEP => grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TKEEP,
        out_stream_TSTRB => grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TSTRB,
        out_stream_TLAST => grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TLAST);

    CTRL_s_axi_U : component fir_filter_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        coeffs_0 => coeffs_0,
        coeffs_1 => coeffs_1,
        coeffs_2 => coeffs_2,
        coeffs_3 => coeffs_3,
        coeffs_4 => coeffs_4,
        coeffs_5 => coeffs_5,
        coeffs_6 => coeffs_6,
        coeffs_7 => coeffs_7,
        coeffs_8 => coeffs_8,
        coeffs_9 => coeffs_9,
        coeffs_10 => coeffs_10,
        coeffs_11 => coeffs_11,
        coeffs_12 => coeffs_12,
        coeffs_13 => coeffs_13,
        coeffs_14 => coeffs_14,
        coeffs_15 => coeffs_15,
        coeffs_16 => coeffs_16,
        coeffs_17 => coeffs_17,
        coeffs_18 => coeffs_18,
        coeffs_19 => coeffs_19,
        coeffs_20 => coeffs_20,
        coeffs_21 => coeffs_21,
        coeffs_22 => coeffs_22,
        coeffs_23 => coeffs_23,
        coeffs_24 => coeffs_24,
        coeffs_25 => coeffs_25,
        coeffs_26 => coeffs_26,
        coeffs_27 => coeffs_27,
        coeffs_28 => coeffs_28,
        coeffs_29 => coeffs_29,
        coeffs_30 => coeffs_30,
        coeffs_31 => coeffs_31,
        num_taps => num_taps,
        num_samples => num_samples,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    regslice_both_in_stream_V_data_V_U : component fir_filter_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_data_V_U_ack_in,
        data_out => in_stream_TDATA_int_regslice,
        vld_out => in_stream_TVALID_int_regslice,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_data_V_U_apdone_blk);

    regslice_both_in_stream_V_keep_V_U : component fir_filter_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TKEEP,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_keep_V_U_ack_in,
        data_out => in_stream_TKEEP_int_regslice,
        vld_out => regslice_both_in_stream_V_keep_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_keep_V_U_apdone_blk);

    regslice_both_in_stream_V_strb_V_U : component fir_filter_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TSTRB,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_strb_V_U_ack_in,
        data_out => in_stream_TSTRB_int_regslice,
        vld_out => regslice_both_in_stream_V_strb_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_strb_V_U_apdone_blk);

    regslice_both_in_stream_V_last_V_U : component fir_filter_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TLAST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_last_V_U_ack_in,
        data_out => in_stream_TLAST_int_regslice,
        vld_out => regslice_both_in_stream_V_last_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_last_V_U_apdone_blk);

    regslice_both_out_stream_V_data_V_U : component fir_filter_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TDATA,
        vld_in => grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TVALID,
        ack_in => out_stream_TREADY_int_regslice,
        data_out => out_stream_TDATA,
        vld_out => regslice_both_out_stream_V_data_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_data_V_U_apdone_blk);

    regslice_both_out_stream_V_keep_V_U : component fir_filter_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TKEEP,
        vld_in => grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_keep_V_U_ack_in_dummy,
        data_out => out_stream_TKEEP,
        vld_out => regslice_both_out_stream_V_keep_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_keep_V_U_apdone_blk);

    regslice_both_out_stream_V_strb_V_U : component fir_filter_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TSTRB,
        vld_in => grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_strb_V_U_ack_in_dummy,
        data_out => out_stream_TSTRB,
        vld_out => regslice_both_out_stream_V_strb_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_strb_V_U_apdone_blk);

    regslice_both_out_stream_V_last_V_U : component fir_filter_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TLAST,
        vld_in => grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_last_V_U_ack_in_dummy,
        data_out => out_stream_TLAST,
        vld_out => regslice_both_out_stream_V_last_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_fir_filter_Pipeline_sample_loop_fu_498_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_fir_filter_Pipeline_sample_loop_fu_498_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_fir_filter_Pipeline_sample_loop_fu_498_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_fir_filter_Pipeline_sample_loop_fu_498_ap_ready = ap_const_logic_1)) then 
                    grp_fir_filter_Pipeline_sample_loop_fu_498_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                cmp31_10_reg_1185 <= cmp31_10_fu_774_p2;
                cmp31_11_reg_1190 <= cmp31_11_fu_781_p2;
                cmp31_12_reg_1195 <= cmp31_12_fu_788_p2;
                cmp31_13_reg_1200 <= cmp31_13_fu_795_p2;
                cmp31_14_reg_1205 <= cmp31_14_fu_802_p2;
                cmp31_16_reg_1215 <= cmp31_16_fu_826_p2;
                cmp31_17_reg_1220 <= cmp31_17_fu_833_p2;
                cmp31_18_reg_1225 <= cmp31_18_fu_840_p2;
                cmp31_19_reg_1230 <= cmp31_19_fu_847_p2;
                cmp31_20_reg_1235 <= cmp31_20_fu_854_p2;
                cmp31_21_reg_1240 <= cmp31_21_fu_861_p2;
                cmp31_22_reg_1245 <= cmp31_22_fu_868_p2;
                cmp31_23_reg_1250 <= cmp31_23_fu_875_p2;
                cmp31_24_reg_1255 <= cmp31_24_fu_882_p2;
                cmp31_25_reg_1260 <= cmp31_25_fu_889_p2;
                cmp31_26_reg_1265 <= cmp31_26_fu_896_p2;
                cmp31_27_reg_1270 <= cmp31_27_fu_903_p2;
                cmp31_28_reg_1275 <= cmp31_28_fu_910_p2;
                cmp31_29_reg_1280 <= cmp31_29_fu_917_p2;
                cmp31_2_reg_1145 <= cmp31_2_fu_698_p2;
                cmp31_30_reg_1285 <= cmp31_30_fu_924_p2;
                cmp31_4_reg_1155 <= cmp31_4_fu_722_p2;
                cmp31_5_reg_1160 <= cmp31_5_fu_729_p2;
                cmp31_6_reg_1165 <= cmp31_6_fu_736_p2;
                cmp31_8_reg_1175 <= cmp31_8_fu_760_p2;
                cmp31_9_reg_1180 <= cmp31_9_fu_767_p2;
                icmp10_reg_1210 <= icmp10_fu_819_p2;
                icmp4_reg_1150 <= icmp4_fu_715_p2;
                icmp7_reg_1170 <= icmp7_fu_753_p2;
                icmp_reg_1140 <= icmp_fu_691_p2;
                select_ln44_1_reg_1295 <= select_ln44_1_fu_950_p3;
                tmp_5_reg_1290 <= select_ln33_fu_675_p3(5 downto 5);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                coeffs_0_read_reg_974 <= coeffs_0;
                coeffs_10_read_reg_1024 <= coeffs_10;
                coeffs_11_read_reg_1029 <= coeffs_11;
                coeffs_12_read_reg_1034 <= coeffs_12;
                coeffs_13_read_reg_1039 <= coeffs_13;
                coeffs_14_read_reg_1044 <= coeffs_14;
                coeffs_15_read_reg_1049 <= coeffs_15;
                coeffs_16_read_reg_1054 <= coeffs_16;
                coeffs_17_read_reg_1059 <= coeffs_17;
                coeffs_18_read_reg_1064 <= coeffs_18;
                coeffs_19_read_reg_1069 <= coeffs_19;
                coeffs_1_read_reg_979 <= coeffs_1;
                coeffs_20_read_reg_1074 <= coeffs_20;
                coeffs_21_read_reg_1079 <= coeffs_21;
                coeffs_22_read_reg_1084 <= coeffs_22;
                coeffs_23_read_reg_1089 <= coeffs_23;
                coeffs_24_read_reg_1094 <= coeffs_24;
                coeffs_25_read_reg_1099 <= coeffs_25;
                coeffs_26_read_reg_1104 <= coeffs_26;
                coeffs_27_read_reg_1109 <= coeffs_27;
                coeffs_28_read_reg_1114 <= coeffs_28;
                coeffs_29_read_reg_1119 <= coeffs_29;
                coeffs_2_read_reg_984 <= coeffs_2;
                coeffs_30_read_reg_1124 <= coeffs_30;
                coeffs_31_read_reg_1129 <= coeffs_31;
                coeffs_3_read_reg_989 <= coeffs_3;
                coeffs_4_read_reg_994 <= coeffs_4;
                coeffs_5_read_reg_999 <= coeffs_5;
                coeffs_6_read_reg_1004 <= coeffs_6;
                coeffs_7_read_reg_1009 <= coeffs_7;
                coeffs_8_read_reg_1014 <= coeffs_8;
                coeffs_9_read_reg_1019 <= coeffs_9;
                icmp_ln33_reg_964 <= icmp_ln33_fu_609_p2;
                select_ln44_reg_1134 <= select_ln44_fu_667_p3;
                sub50_reg_969 <= sub50_fu_647_p3;
                trunc_ln7_reg_959 <= trunc_ln7_fu_605_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_fir_filter_Pipeline_sample_loop_fu_498_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state4, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_fir_filter_Pipeline_sample_loop_fu_498_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_fir_filter_Pipeline_sample_loop_fu_498_ap_done)
    begin
        if ((grp_fir_filter_Pipeline_sample_loop_fu_498_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state4, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    cmp31_10_fu_774_p2 <= "1" when (unsigned(select_ln33_fu_675_p3) > unsigned(ap_const_lv6_A)) else "0";
    cmp31_11_fu_781_p2 <= "1" when (unsigned(select_ln33_fu_675_p3) > unsigned(ap_const_lv6_B)) else "0";
    cmp31_12_fu_788_p2 <= "1" when (unsigned(select_ln33_fu_675_p3) > unsigned(ap_const_lv6_C)) else "0";
    cmp31_13_fu_795_p2 <= "1" when (unsigned(select_ln33_fu_675_p3) > unsigned(ap_const_lv6_D)) else "0";
    cmp31_14_fu_802_p2 <= "1" when (unsigned(select_ln33_fu_675_p3) > unsigned(ap_const_lv6_E)) else "0";
    cmp31_16_fu_826_p2 <= "1" when (unsigned(select_ln33_fu_675_p3) > unsigned(ap_const_lv6_10)) else "0";
    cmp31_17_fu_833_p2 <= "1" when (unsigned(select_ln33_fu_675_p3) > unsigned(ap_const_lv6_11)) else "0";
    cmp31_18_fu_840_p2 <= "1" when (unsigned(select_ln33_fu_675_p3) > unsigned(ap_const_lv6_12)) else "0";
    cmp31_19_fu_847_p2 <= "1" when (unsigned(select_ln33_fu_675_p3) > unsigned(ap_const_lv6_13)) else "0";
    cmp31_20_fu_854_p2 <= "1" when (unsigned(select_ln33_fu_675_p3) > unsigned(ap_const_lv6_14)) else "0";
    cmp31_21_fu_861_p2 <= "1" when (unsigned(select_ln33_fu_675_p3) > unsigned(ap_const_lv6_15)) else "0";
    cmp31_22_fu_868_p2 <= "1" when (unsigned(select_ln33_fu_675_p3) > unsigned(ap_const_lv6_16)) else "0";
    cmp31_23_fu_875_p2 <= "1" when (unsigned(select_ln33_fu_675_p3) > unsigned(ap_const_lv6_17)) else "0";
    cmp31_24_fu_882_p2 <= "1" when (unsigned(select_ln33_fu_675_p3) > unsigned(ap_const_lv6_18)) else "0";
    cmp31_25_fu_889_p2 <= "1" when (unsigned(select_ln33_fu_675_p3) > unsigned(ap_const_lv6_19)) else "0";
    cmp31_26_fu_896_p2 <= "1" when (unsigned(select_ln33_fu_675_p3) > unsigned(ap_const_lv6_1A)) else "0";
    cmp31_27_fu_903_p2 <= "1" when (unsigned(select_ln33_fu_675_p3) > unsigned(ap_const_lv6_1B)) else "0";
    cmp31_28_fu_910_p2 <= "1" when (unsigned(select_ln33_fu_675_p3) > unsigned(ap_const_lv6_1C)) else "0";
    cmp31_29_fu_917_p2 <= "1" when (unsigned(select_ln33_fu_675_p3) > unsigned(ap_const_lv6_1D)) else "0";
    cmp31_2_fu_698_p2 <= "1" when (unsigned(select_ln33_fu_675_p3) > unsigned(ap_const_lv6_2)) else "0";
    cmp31_30_fu_924_p2 <= "1" when (unsigned(select_ln33_fu_675_p3) > unsigned(ap_const_lv6_1E)) else "0";
    cmp31_4_fu_722_p2 <= "1" when (unsigned(select_ln33_fu_675_p3) > unsigned(ap_const_lv6_4)) else "0";
    cmp31_5_fu_729_p2 <= "1" when (unsigned(select_ln33_fu_675_p3) > unsigned(ap_const_lv6_5)) else "0";
    cmp31_6_fu_736_p2 <= "1" when (unsigned(select_ln33_fu_675_p3) > unsigned(ap_const_lv6_6)) else "0";
    cmp31_8_fu_760_p2 <= "1" when (unsigned(select_ln33_fu_675_p3) > unsigned(ap_const_lv6_8)) else "0";
    cmp31_9_fu_767_p2 <= "1" when (unsigned(select_ln33_fu_675_p3) > unsigned(ap_const_lv6_9)) else "0";
    empty_49_fu_940_p2 <= "1" when (signed(select_ln44_reg_1134) > signed(ap_const_lv32_FFFFFBFF)) else "0";
    empty_fu_655_p2 <= "1" when (signed(num_samples) > signed(ap_const_lv32_0)) else "0";
    grp_fir_filter_Pipeline_sample_loop_fu_498_ap_start <= grp_fir_filter_Pipeline_sample_loop_fu_498_ap_start_reg;
    grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TREADY <= (out_stream_TREADY_int_regslice and ap_CS_fsm_state3);
    icmp10_fu_819_p2 <= "0" when (tmp_4_fu_809_p4 = ap_const_lv2_0) else "1";
    icmp4_fu_715_p2 <= "0" when (tmp_2_fu_705_p4 = ap_const_lv4_0) else "1";
    icmp7_fu_753_p2 <= "0" when (tmp_3_fu_743_p4 = ap_const_lv3_0) else "1";
    icmp_fu_691_p2 <= "0" when (tmp_1_fu_681_p4 = ap_const_lv5_0) else "1";
    icmp_ln30_fu_591_p2 <= "1" when (signed(num_taps) < signed(ap_const_lv32_1)) else "0";
    icmp_ln33_fu_609_p2 <= "1" when (unsigned(select_ln30_fu_597_p3) > unsigned(ap_const_lv31_20)) else "0";
    icmp_ln39_fu_635_p2 <= "1" when (unsigned(select_ln36_fu_623_p3) > unsigned(ap_const_lv31_400)) else "0";
    in_stream_TREADY <= regslice_both_in_stream_V_data_V_U_ack_in;

    in_stream_TREADY_int_regslice_assign_proc : process(grp_fir_filter_Pipeline_sample_loop_fu_498_in_stream_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_stream_TREADY_int_regslice <= grp_fir_filter_Pipeline_sample_loop_fu_498_in_stream_TREADY;
        else 
            in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    num_samples_addr_0_op_fu_641_p2 <= std_logic_vector(unsigned(trunc_ln8_fu_631_p1) + unsigned(ap_const_lv11_7FF));
    out_stream_TVALID <= regslice_both_out_stream_V_data_V_U_vld_out;
    out_stream_TVALID_int_regslice <= grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TVALID;
    select_ln30_fu_597_p3 <= 
        ap_const_lv31_1 when (icmp_ln30_fu_591_p2(0) = '1') else 
        trunc_ln3_1_fu_587_p1;
    select_ln33_fu_675_p3 <= 
        ap_const_lv6_20 when (icmp_ln33_reg_964(0) = '1') else 
        trunc_ln7_reg_959;
    select_ln36_fu_623_p3 <= 
        ap_const_lv31_0 when (tmp_fu_615_p3(0) = '1') else 
        trunc_ln3_fu_583_p1;
    select_ln44_1_fu_950_p3 <= 
        xor_ln44_1_fu_945_p2 when (empty_49_fu_940_p2(0) = '1') else 
        ap_const_lv32_400;
    select_ln44_fu_667_p3 <= 
        xor_ln44_fu_661_p2 when (empty_fu_655_p2(0) = '1') else 
        ap_const_lv32_FFFFFFFF;
    sub50_fu_647_p3 <= 
        ap_const_lv11_3FF when (icmp_ln39_fu_635_p2(0) = '1') else 
        num_samples_addr_0_op_fu_641_p2;
    tmp_1_fu_681_p4 <= select_ln33_fu_675_p3(5 downto 1);
    tmp_2_fu_705_p4 <= select_ln33_fu_675_p3(5 downto 2);
    tmp_3_fu_743_p4 <= select_ln33_fu_675_p3(5 downto 3);
    tmp_4_fu_809_p4 <= select_ln33_fu_675_p3(5 downto 4);
    tmp_fu_615_p3 <= num_samples(31 downto 31);
    trunc_ln3_1_fu_587_p1 <= num_taps(31 - 1 downto 0);
    trunc_ln3_fu_583_p1 <= num_samples(31 - 1 downto 0);
    trunc_ln7_fu_605_p1 <= select_ln30_fu_597_p3(6 - 1 downto 0);
    trunc_ln8_fu_631_p1 <= select_ln36_fu_623_p3(11 - 1 downto 0);
    xor_ln44_1_fu_945_p2 <= (select_ln44_reg_1134 xor ap_const_lv32_FFFFFFFF);
    xor_ln44_fu_661_p2 <= (num_samples xor ap_const_lv32_FFFFFFFF);
end behav;
