// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fir_filter_fir_filter,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.807562,HLS_SYN_LAT=549,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=4748,HLS_SYN_LUT=3572,HLS_VERSION=2024_1}" *)

module fir_filter (
        ap_clk,
        ap_rst_n,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 9;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [15:0] coeffs_0;
wire   [15:0] coeffs_1;
wire   [15:0] coeffs_2;
wire   [15:0] coeffs_3;
wire   [15:0] coeffs_4;
wire   [15:0] coeffs_5;
wire   [15:0] coeffs_6;
wire   [15:0] coeffs_7;
wire   [15:0] coeffs_8;
wire   [15:0] coeffs_9;
wire   [15:0] coeffs_10;
wire   [15:0] coeffs_11;
wire   [15:0] coeffs_12;
wire   [15:0] coeffs_13;
wire   [15:0] coeffs_14;
wire   [15:0] coeffs_15;
wire   [15:0] coeffs_16;
wire   [15:0] coeffs_17;
wire   [15:0] coeffs_18;
wire   [15:0] coeffs_19;
wire   [15:0] coeffs_20;
wire   [15:0] coeffs_21;
wire   [15:0] coeffs_22;
wire   [15:0] coeffs_23;
wire   [15:0] coeffs_24;
wire   [15:0] coeffs_25;
wire   [15:0] coeffs_26;
wire   [15:0] coeffs_27;
wire   [15:0] coeffs_28;
wire   [15:0] coeffs_29;
wire   [15:0] coeffs_30;
wire   [15:0] coeffs_31;
wire   [31:0] num_taps;
wire   [31:0] num_samples;
wire   [5:0] trunc_ln7_fu_605_p1;
reg   [5:0] trunc_ln7_reg_959;
wire   [0:0] icmp_ln33_fu_609_p2;
reg   [0:0] icmp_ln33_reg_964;
wire   [10:0] sub50_fu_647_p3;
reg   [10:0] sub50_reg_969;
reg   [15:0] coeffs_0_read_reg_974;
reg   [15:0] coeffs_1_read_reg_979;
reg   [15:0] coeffs_2_read_reg_984;
reg   [15:0] coeffs_3_read_reg_989;
reg   [15:0] coeffs_4_read_reg_994;
reg   [15:0] coeffs_5_read_reg_999;
reg   [15:0] coeffs_6_read_reg_1004;
reg   [15:0] coeffs_7_read_reg_1009;
reg   [15:0] coeffs_8_read_reg_1014;
reg   [15:0] coeffs_9_read_reg_1019;
reg   [15:0] coeffs_10_read_reg_1024;
reg   [15:0] coeffs_11_read_reg_1029;
reg   [15:0] coeffs_12_read_reg_1034;
reg   [15:0] coeffs_13_read_reg_1039;
reg   [15:0] coeffs_14_read_reg_1044;
reg   [15:0] coeffs_15_read_reg_1049;
reg   [15:0] coeffs_16_read_reg_1054;
reg   [15:0] coeffs_17_read_reg_1059;
reg   [15:0] coeffs_18_read_reg_1064;
reg   [15:0] coeffs_19_read_reg_1069;
reg   [15:0] coeffs_20_read_reg_1074;
reg   [15:0] coeffs_21_read_reg_1079;
reg   [15:0] coeffs_22_read_reg_1084;
reg   [15:0] coeffs_23_read_reg_1089;
reg   [15:0] coeffs_24_read_reg_1094;
reg   [15:0] coeffs_25_read_reg_1099;
reg   [15:0] coeffs_26_read_reg_1104;
reg   [15:0] coeffs_27_read_reg_1109;
reg   [15:0] coeffs_28_read_reg_1114;
reg   [15:0] coeffs_29_read_reg_1119;
reg   [15:0] coeffs_30_read_reg_1124;
reg   [15:0] coeffs_31_read_reg_1129;
wire   [31:0] select_ln44_fu_667_p3;
reg   [31:0] select_ln44_reg_1134;
wire   [0:0] icmp_fu_691_p2;
reg   [0:0] icmp_reg_1140;
wire    ap_CS_fsm_state2;
wire   [0:0] cmp31_2_fu_698_p2;
reg   [0:0] cmp31_2_reg_1145;
wire   [0:0] icmp4_fu_715_p2;
reg   [0:0] icmp4_reg_1150;
wire   [0:0] cmp31_4_fu_722_p2;
reg   [0:0] cmp31_4_reg_1155;
wire   [0:0] cmp31_5_fu_729_p2;
reg   [0:0] cmp31_5_reg_1160;
wire   [0:0] cmp31_6_fu_736_p2;
reg   [0:0] cmp31_6_reg_1165;
wire   [0:0] icmp7_fu_753_p2;
reg   [0:0] icmp7_reg_1170;
wire   [0:0] cmp31_8_fu_760_p2;
reg   [0:0] cmp31_8_reg_1175;
wire   [0:0] cmp31_9_fu_767_p2;
reg   [0:0] cmp31_9_reg_1180;
wire   [0:0] cmp31_10_fu_774_p2;
reg   [0:0] cmp31_10_reg_1185;
wire   [0:0] cmp31_11_fu_781_p2;
reg   [0:0] cmp31_11_reg_1190;
wire   [0:0] cmp31_12_fu_788_p2;
reg   [0:0] cmp31_12_reg_1195;
wire   [0:0] cmp31_13_fu_795_p2;
reg   [0:0] cmp31_13_reg_1200;
wire   [0:0] cmp31_14_fu_802_p2;
reg   [0:0] cmp31_14_reg_1205;
wire   [0:0] icmp10_fu_819_p2;
reg   [0:0] icmp10_reg_1210;
wire   [0:0] cmp31_16_fu_826_p2;
reg   [0:0] cmp31_16_reg_1215;
wire   [0:0] cmp31_17_fu_833_p2;
reg   [0:0] cmp31_17_reg_1220;
wire   [0:0] cmp31_18_fu_840_p2;
reg   [0:0] cmp31_18_reg_1225;
wire   [0:0] cmp31_19_fu_847_p2;
reg   [0:0] cmp31_19_reg_1230;
wire   [0:0] cmp31_20_fu_854_p2;
reg   [0:0] cmp31_20_reg_1235;
wire   [0:0] cmp31_21_fu_861_p2;
reg   [0:0] cmp31_21_reg_1240;
wire   [0:0] cmp31_22_fu_868_p2;
reg   [0:0] cmp31_22_reg_1245;
wire   [0:0] cmp31_23_fu_875_p2;
reg   [0:0] cmp31_23_reg_1250;
wire   [0:0] cmp31_24_fu_882_p2;
reg   [0:0] cmp31_24_reg_1255;
wire   [0:0] cmp31_25_fu_889_p2;
reg   [0:0] cmp31_25_reg_1260;
wire   [0:0] cmp31_26_fu_896_p2;
reg   [0:0] cmp31_26_reg_1265;
wire   [0:0] cmp31_27_fu_903_p2;
reg   [0:0] cmp31_27_reg_1270;
wire   [0:0] cmp31_28_fu_910_p2;
reg   [0:0] cmp31_28_reg_1275;
wire   [0:0] cmp31_29_fu_917_p2;
reg   [0:0] cmp31_29_reg_1280;
wire   [0:0] cmp31_30_fu_924_p2;
reg   [0:0] cmp31_30_reg_1285;
reg   [0:0] tmp_5_reg_1290;
wire   [31:0] select_ln44_1_fu_950_p3;
reg   [31:0] select_ln44_1_reg_1295;
wire    grp_fir_filter_Pipeline_sample_loop_fu_498_ap_start;
wire    grp_fir_filter_Pipeline_sample_loop_fu_498_ap_done;
wire    grp_fir_filter_Pipeline_sample_loop_fu_498_ap_idle;
wire    grp_fir_filter_Pipeline_sample_loop_fu_498_ap_ready;
wire    grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TREADY;
wire    grp_fir_filter_Pipeline_sample_loop_fu_498_in_stream_TREADY;
wire   [31:0] grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TDATA;
wire    grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TVALID;
wire   [3:0] grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TKEEP;
wire   [3:0] grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TSTRB;
wire   [0:0] grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TLAST;
reg    grp_fir_filter_Pipeline_sample_loop_fu_498_ap_start_reg;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln30_fu_591_p2;
wire   [30:0] trunc_ln3_1_fu_587_p1;
wire   [30:0] select_ln30_fu_597_p3;
wire   [0:0] tmp_fu_615_p3;
wire   [30:0] trunc_ln3_fu_583_p1;
wire   [30:0] select_ln36_fu_623_p3;
wire   [10:0] trunc_ln8_fu_631_p1;
wire   [0:0] icmp_ln39_fu_635_p2;
wire   [10:0] num_samples_addr_0_op_fu_641_p2;
wire   [0:0] empty_fu_655_p2;
wire   [31:0] xor_ln44_fu_661_p2;
wire   [5:0] select_ln33_fu_675_p3;
wire   [4:0] tmp_1_fu_681_p4;
wire   [3:0] tmp_2_fu_705_p4;
wire   [2:0] tmp_3_fu_743_p4;
wire   [1:0] tmp_4_fu_809_p4;
wire   [0:0] empty_49_fu_940_p2;
wire   [31:0] xor_ln44_1_fu_945_p2;
wire    ap_CS_fsm_state4;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [31:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [3:0] in_stream_TKEEP_int_regslice;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [3:0] in_stream_TSTRB_int_regslice;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int_regslice;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
wire    out_stream_TVALID_int_regslice;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_fir_filter_Pipeline_sample_loop_fu_498_ap_start_reg = 1'b0;
end

fir_filter_fir_filter_Pipeline_sample_loop grp_fir_filter_Pipeline_sample_loop_fu_498(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_fir_filter_Pipeline_sample_loop_fu_498_ap_start),
    .ap_done(grp_fir_filter_Pipeline_sample_loop_fu_498_ap_done),
    .ap_idle(grp_fir_filter_Pipeline_sample_loop_fu_498_ap_idle),
    .ap_ready(grp_fir_filter_Pipeline_sample_loop_fu_498_ap_ready),
    .in_stream_TVALID(in_stream_TVALID_int_regslice),
    .out_stream_TREADY(grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TREADY),
    .select_ln44_1(select_ln44_1_reg_1295),
    .in_stream_TDATA(in_stream_TDATA_int_regslice),
    .in_stream_TREADY(grp_fir_filter_Pipeline_sample_loop_fu_498_in_stream_TREADY),
    .in_stream_TKEEP(in_stream_TKEEP_int_regslice),
    .in_stream_TSTRB(in_stream_TSTRB_int_regslice),
    .in_stream_TLAST(in_stream_TLAST_int_regslice),
    .coeffs_0_load_cast(coeffs_0_read_reg_974),
    .coeffs_1_load_cast(coeffs_1_read_reg_979),
    .icmp(icmp_reg_1140),
    .coeffs_2_load_cast(coeffs_2_read_reg_984),
    .cmp31_2(cmp31_2_reg_1145),
    .coeffs_3_load_cast(coeffs_3_read_reg_989),
    .icmp4(icmp4_reg_1150),
    .coeffs_4_load_cast(coeffs_4_read_reg_994),
    .cmp31_4(cmp31_4_reg_1155),
    .coeffs_5_load_cast(coeffs_5_read_reg_999),
    .cmp31_5(cmp31_5_reg_1160),
    .coeffs_6_load_cast(coeffs_6_read_reg_1004),
    .cmp31_6(cmp31_6_reg_1165),
    .coeffs_7_load_cast(coeffs_7_read_reg_1009),
    .icmp7(icmp7_reg_1170),
    .coeffs_8_load_cast(coeffs_8_read_reg_1014),
    .cmp31_8(cmp31_8_reg_1175),
    .coeffs_9_load_cast(coeffs_9_read_reg_1019),
    .cmp31_9(cmp31_9_reg_1180),
    .coeffs_10_load_cast(coeffs_10_read_reg_1024),
    .cmp31_10(cmp31_10_reg_1185),
    .coeffs_11_load_cast(coeffs_11_read_reg_1029),
    .cmp31_11(cmp31_11_reg_1190),
    .coeffs_12_load_cast(coeffs_12_read_reg_1034),
    .cmp31_12(cmp31_12_reg_1195),
    .coeffs_13_load_cast(coeffs_13_read_reg_1039),
    .cmp31_13(cmp31_13_reg_1200),
    .coeffs_14_load_cast(coeffs_14_read_reg_1044),
    .cmp31_14(cmp31_14_reg_1205),
    .coeffs_15_load_cast(coeffs_15_read_reg_1049),
    .icmp10(icmp10_reg_1210),
    .coeffs_16_load_cast(coeffs_16_read_reg_1054),
    .cmp31_16(cmp31_16_reg_1215),
    .coeffs_17_load_cast(coeffs_17_read_reg_1059),
    .cmp31_17(cmp31_17_reg_1220),
    .coeffs_18_load_cast(coeffs_18_read_reg_1064),
    .cmp31_18(cmp31_18_reg_1225),
    .coeffs_19_load_cast(coeffs_19_read_reg_1069),
    .cmp31_19(cmp31_19_reg_1230),
    .coeffs_20_load_cast(coeffs_20_read_reg_1074),
    .cmp31_20(cmp31_20_reg_1235),
    .coeffs_21_load_cast(coeffs_21_read_reg_1079),
    .cmp31_21(cmp31_21_reg_1240),
    .coeffs_22_load_cast(coeffs_22_read_reg_1084),
    .cmp31_22(cmp31_22_reg_1245),
    .coeffs_23_load_cast(coeffs_23_read_reg_1089),
    .cmp31_23(cmp31_23_reg_1250),
    .coeffs_24_load_cast(coeffs_24_read_reg_1094),
    .cmp31_24(cmp31_24_reg_1255),
    .coeffs_25_load_cast(coeffs_25_read_reg_1099),
    .cmp31_25(cmp31_25_reg_1260),
    .coeffs_26_load_cast(coeffs_26_read_reg_1104),
    .cmp31_26(cmp31_26_reg_1265),
    .coeffs_27_load_cast(coeffs_27_read_reg_1109),
    .cmp31_27(cmp31_27_reg_1270),
    .coeffs_28_load_cast(coeffs_28_read_reg_1114),
    .cmp31_28(cmp31_28_reg_1275),
    .coeffs_29_load_cast(coeffs_29_read_reg_1119),
    .cmp31_29(cmp31_29_reg_1280),
    .coeffs_30_load_cast(coeffs_30_read_reg_1124),
    .cmp31_30(cmp31_30_reg_1285),
    .coeffs_31_load_cast(coeffs_31_read_reg_1129),
    .empty(tmp_5_reg_1290),
    .sext_ln44(sub50_reg_969),
    .out_stream_TDATA(grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TDATA),
    .out_stream_TVALID(grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TVALID),
    .out_stream_TKEEP(grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TKEEP),
    .out_stream_TSTRB(grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TSTRB),
    .out_stream_TLAST(grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TLAST)
);

fir_filter_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .coeffs_0(coeffs_0),
    .coeffs_1(coeffs_1),
    .coeffs_2(coeffs_2),
    .coeffs_3(coeffs_3),
    .coeffs_4(coeffs_4),
    .coeffs_5(coeffs_5),
    .coeffs_6(coeffs_6),
    .coeffs_7(coeffs_7),
    .coeffs_8(coeffs_8),
    .coeffs_9(coeffs_9),
    .coeffs_10(coeffs_10),
    .coeffs_11(coeffs_11),
    .coeffs_12(coeffs_12),
    .coeffs_13(coeffs_13),
    .coeffs_14(coeffs_14),
    .coeffs_15(coeffs_15),
    .coeffs_16(coeffs_16),
    .coeffs_17(coeffs_17),
    .coeffs_18(coeffs_18),
    .coeffs_19(coeffs_19),
    .coeffs_20(coeffs_20),
    .coeffs_21(coeffs_21),
    .coeffs_22(coeffs_22),
    .coeffs_23(coeffs_23),
    .coeffs_24(coeffs_24),
    .coeffs_25(coeffs_25),
    .coeffs_26(coeffs_26),
    .coeffs_27(coeffs_27),
    .coeffs_28(coeffs_28),
    .coeffs_29(coeffs_29),
    .coeffs_30(coeffs_30),
    .coeffs_31(coeffs_31),
    .num_taps(num_taps),
    .num_samples(num_samples),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

fir_filter_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

fir_filter_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

fir_filter_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

fir_filter_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int_regslice),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

fir_filter_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TDATA),
    .vld_in(grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TVALID),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

fir_filter_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TKEEP),
    .vld_in(grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

fir_filter_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TSTRB),
    .vld_in(grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

fir_filter_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TLAST),
    .vld_in(grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_fir_filter_Pipeline_sample_loop_fu_498_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_fir_filter_Pipeline_sample_loop_fu_498_ap_start_reg <= 1'b1;
        end else if ((grp_fir_filter_Pipeline_sample_loop_fu_498_ap_ready == 1'b1)) begin
            grp_fir_filter_Pipeline_sample_loop_fu_498_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cmp31_10_reg_1185 <= cmp31_10_fu_774_p2;
        cmp31_11_reg_1190 <= cmp31_11_fu_781_p2;
        cmp31_12_reg_1195 <= cmp31_12_fu_788_p2;
        cmp31_13_reg_1200 <= cmp31_13_fu_795_p2;
        cmp31_14_reg_1205 <= cmp31_14_fu_802_p2;
        cmp31_16_reg_1215 <= cmp31_16_fu_826_p2;
        cmp31_17_reg_1220 <= cmp31_17_fu_833_p2;
        cmp31_18_reg_1225 <= cmp31_18_fu_840_p2;
        cmp31_19_reg_1230 <= cmp31_19_fu_847_p2;
        cmp31_20_reg_1235 <= cmp31_20_fu_854_p2;
        cmp31_21_reg_1240 <= cmp31_21_fu_861_p2;
        cmp31_22_reg_1245 <= cmp31_22_fu_868_p2;
        cmp31_23_reg_1250 <= cmp31_23_fu_875_p2;
        cmp31_24_reg_1255 <= cmp31_24_fu_882_p2;
        cmp31_25_reg_1260 <= cmp31_25_fu_889_p2;
        cmp31_26_reg_1265 <= cmp31_26_fu_896_p2;
        cmp31_27_reg_1270 <= cmp31_27_fu_903_p2;
        cmp31_28_reg_1275 <= cmp31_28_fu_910_p2;
        cmp31_29_reg_1280 <= cmp31_29_fu_917_p2;
        cmp31_2_reg_1145 <= cmp31_2_fu_698_p2;
        cmp31_30_reg_1285 <= cmp31_30_fu_924_p2;
        cmp31_4_reg_1155 <= cmp31_4_fu_722_p2;
        cmp31_5_reg_1160 <= cmp31_5_fu_729_p2;
        cmp31_6_reg_1165 <= cmp31_6_fu_736_p2;
        cmp31_8_reg_1175 <= cmp31_8_fu_760_p2;
        cmp31_9_reg_1180 <= cmp31_9_fu_767_p2;
        icmp10_reg_1210 <= icmp10_fu_819_p2;
        icmp4_reg_1150 <= icmp4_fu_715_p2;
        icmp7_reg_1170 <= icmp7_fu_753_p2;
        icmp_reg_1140 <= icmp_fu_691_p2;
        select_ln44_1_reg_1295 <= select_ln44_1_fu_950_p3;
        tmp_5_reg_1290 <= select_ln33_fu_675_p3[32'd5];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        coeffs_0_read_reg_974 <= coeffs_0;
        coeffs_10_read_reg_1024 <= coeffs_10;
        coeffs_11_read_reg_1029 <= coeffs_11;
        coeffs_12_read_reg_1034 <= coeffs_12;
        coeffs_13_read_reg_1039 <= coeffs_13;
        coeffs_14_read_reg_1044 <= coeffs_14;
        coeffs_15_read_reg_1049 <= coeffs_15;
        coeffs_16_read_reg_1054 <= coeffs_16;
        coeffs_17_read_reg_1059 <= coeffs_17;
        coeffs_18_read_reg_1064 <= coeffs_18;
        coeffs_19_read_reg_1069 <= coeffs_19;
        coeffs_1_read_reg_979 <= coeffs_1;
        coeffs_20_read_reg_1074 <= coeffs_20;
        coeffs_21_read_reg_1079 <= coeffs_21;
        coeffs_22_read_reg_1084 <= coeffs_22;
        coeffs_23_read_reg_1089 <= coeffs_23;
        coeffs_24_read_reg_1094 <= coeffs_24;
        coeffs_25_read_reg_1099 <= coeffs_25;
        coeffs_26_read_reg_1104 <= coeffs_26;
        coeffs_27_read_reg_1109 <= coeffs_27;
        coeffs_28_read_reg_1114 <= coeffs_28;
        coeffs_29_read_reg_1119 <= coeffs_29;
        coeffs_2_read_reg_984 <= coeffs_2;
        coeffs_30_read_reg_1124 <= coeffs_30;
        coeffs_31_read_reg_1129 <= coeffs_31;
        coeffs_3_read_reg_989 <= coeffs_3;
        coeffs_4_read_reg_994 <= coeffs_4;
        coeffs_5_read_reg_999 <= coeffs_5;
        coeffs_6_read_reg_1004 <= coeffs_6;
        coeffs_7_read_reg_1009 <= coeffs_7;
        coeffs_8_read_reg_1014 <= coeffs_8;
        coeffs_9_read_reg_1019 <= coeffs_9;
        icmp_ln33_reg_964 <= icmp_ln33_fu_609_p2;
        select_ln44_reg_1134 <= select_ln44_fu_667_p3;
        sub50_reg_969 <= sub50_fu_647_p3;
        trunc_ln7_reg_959 <= trunc_ln7_fu_605_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_fir_filter_Pipeline_sample_loop_fu_498_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_stream_TREADY_int_regslice = grp_fir_filter_Pipeline_sample_loop_fu_498_in_stream_TREADY;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_fir_filter_Pipeline_sample_loop_fu_498_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign cmp31_10_fu_774_p2 = ((select_ln33_fu_675_p3 > 6'd10) ? 1'b1 : 1'b0);

assign cmp31_11_fu_781_p2 = ((select_ln33_fu_675_p3 > 6'd11) ? 1'b1 : 1'b0);

assign cmp31_12_fu_788_p2 = ((select_ln33_fu_675_p3 > 6'd12) ? 1'b1 : 1'b0);

assign cmp31_13_fu_795_p2 = ((select_ln33_fu_675_p3 > 6'd13) ? 1'b1 : 1'b0);

assign cmp31_14_fu_802_p2 = ((select_ln33_fu_675_p3 > 6'd14) ? 1'b1 : 1'b0);

assign cmp31_16_fu_826_p2 = ((select_ln33_fu_675_p3 > 6'd16) ? 1'b1 : 1'b0);

assign cmp31_17_fu_833_p2 = ((select_ln33_fu_675_p3 > 6'd17) ? 1'b1 : 1'b0);

assign cmp31_18_fu_840_p2 = ((select_ln33_fu_675_p3 > 6'd18) ? 1'b1 : 1'b0);

assign cmp31_19_fu_847_p2 = ((select_ln33_fu_675_p3 > 6'd19) ? 1'b1 : 1'b0);

assign cmp31_20_fu_854_p2 = ((select_ln33_fu_675_p3 > 6'd20) ? 1'b1 : 1'b0);

assign cmp31_21_fu_861_p2 = ((select_ln33_fu_675_p3 > 6'd21) ? 1'b1 : 1'b0);

assign cmp31_22_fu_868_p2 = ((select_ln33_fu_675_p3 > 6'd22) ? 1'b1 : 1'b0);

assign cmp31_23_fu_875_p2 = ((select_ln33_fu_675_p3 > 6'd23) ? 1'b1 : 1'b0);

assign cmp31_24_fu_882_p2 = ((select_ln33_fu_675_p3 > 6'd24) ? 1'b1 : 1'b0);

assign cmp31_25_fu_889_p2 = ((select_ln33_fu_675_p3 > 6'd25) ? 1'b1 : 1'b0);

assign cmp31_26_fu_896_p2 = ((select_ln33_fu_675_p3 > 6'd26) ? 1'b1 : 1'b0);

assign cmp31_27_fu_903_p2 = ((select_ln33_fu_675_p3 > 6'd27) ? 1'b1 : 1'b0);

assign cmp31_28_fu_910_p2 = ((select_ln33_fu_675_p3 > 6'd28) ? 1'b1 : 1'b0);

assign cmp31_29_fu_917_p2 = ((select_ln33_fu_675_p3 > 6'd29) ? 1'b1 : 1'b0);

assign cmp31_2_fu_698_p2 = ((select_ln33_fu_675_p3 > 6'd2) ? 1'b1 : 1'b0);

assign cmp31_30_fu_924_p2 = ((select_ln33_fu_675_p3 > 6'd30) ? 1'b1 : 1'b0);

assign cmp31_4_fu_722_p2 = ((select_ln33_fu_675_p3 > 6'd4) ? 1'b1 : 1'b0);

assign cmp31_5_fu_729_p2 = ((select_ln33_fu_675_p3 > 6'd5) ? 1'b1 : 1'b0);

assign cmp31_6_fu_736_p2 = ((select_ln33_fu_675_p3 > 6'd6) ? 1'b1 : 1'b0);

assign cmp31_8_fu_760_p2 = ((select_ln33_fu_675_p3 > 6'd8) ? 1'b1 : 1'b0);

assign cmp31_9_fu_767_p2 = ((select_ln33_fu_675_p3 > 6'd9) ? 1'b1 : 1'b0);

assign empty_49_fu_940_p2 = (($signed(select_ln44_reg_1134) > $signed(32'd4294966271)) ? 1'b1 : 1'b0);

assign empty_fu_655_p2 = (($signed(num_samples) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign grp_fir_filter_Pipeline_sample_loop_fu_498_ap_start = grp_fir_filter_Pipeline_sample_loop_fu_498_ap_start_reg;

assign grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TREADY = (out_stream_TREADY_int_regslice & ap_CS_fsm_state3);

assign icmp10_fu_819_p2 = ((tmp_4_fu_809_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp4_fu_715_p2 = ((tmp_2_fu_705_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp7_fu_753_p2 = ((tmp_3_fu_743_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_fu_691_p2 = ((tmp_1_fu_681_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln30_fu_591_p2 = (($signed(num_taps) < $signed(32'd1)) ? 1'b1 : 1'b0);

assign icmp_ln33_fu_609_p2 = ((select_ln30_fu_597_p3 > 31'd32) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_635_p2 = ((select_ln36_fu_623_p3 > 31'd1024) ? 1'b1 : 1'b0);

assign in_stream_TREADY = regslice_both_in_stream_V_data_V_U_ack_in;

assign num_samples_addr_0_op_fu_641_p2 = ($signed(trunc_ln8_fu_631_p1) + $signed(11'd2047));

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign out_stream_TVALID_int_regslice = grp_fir_filter_Pipeline_sample_loop_fu_498_out_stream_TVALID;

assign select_ln30_fu_597_p3 = ((icmp_ln30_fu_591_p2[0:0] == 1'b1) ? 31'd1 : trunc_ln3_1_fu_587_p1);

assign select_ln33_fu_675_p3 = ((icmp_ln33_reg_964[0:0] == 1'b1) ? 6'd32 : trunc_ln7_reg_959);

assign select_ln36_fu_623_p3 = ((tmp_fu_615_p3[0:0] == 1'b1) ? 31'd0 : trunc_ln3_fu_583_p1);

assign select_ln44_1_fu_950_p3 = ((empty_49_fu_940_p2[0:0] == 1'b1) ? xor_ln44_1_fu_945_p2 : 32'd1024);

assign select_ln44_fu_667_p3 = ((empty_fu_655_p2[0:0] == 1'b1) ? xor_ln44_fu_661_p2 : 32'd4294967295);

assign sub50_fu_647_p3 = ((icmp_ln39_fu_635_p2[0:0] == 1'b1) ? 11'd1023 : num_samples_addr_0_op_fu_641_p2);

assign tmp_1_fu_681_p4 = {{select_ln33_fu_675_p3[5:1]}};

assign tmp_2_fu_705_p4 = {{select_ln33_fu_675_p3[5:2]}};

assign tmp_3_fu_743_p4 = {{select_ln33_fu_675_p3[5:3]}};

assign tmp_4_fu_809_p4 = {{select_ln33_fu_675_p3[5:4]}};

assign tmp_fu_615_p3 = num_samples[32'd31];

assign trunc_ln3_1_fu_587_p1 = num_taps[30:0];

assign trunc_ln3_fu_583_p1 = num_samples[30:0];

assign trunc_ln7_fu_605_p1 = select_ln30_fu_597_p3[5:0];

assign trunc_ln8_fu_631_p1 = select_ln36_fu_623_p3[10:0];

assign xor_ln44_1_fu_945_p2 = (select_ln44_reg_1134 ^ 32'd4294967295);

assign xor_ln44_fu_661_p2 = (num_samples ^ 32'd4294967295);


reg find_kernel_block = 0;
// synthesis translate_off
`include "fir_filter_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //fir_filter

