// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fir_filter_fir_filter_Pipeline_sample_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_TVALID,
        out_stream_TREADY,
        select_ln44_1,
        in_stream_TDATA,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST,
        coeffs_0_load_cast,
        coeffs_1_load_cast,
        icmp,
        coeffs_2_load_cast,
        cmp31_2,
        coeffs_3_load_cast,
        icmp4,
        coeffs_4_load_cast,
        cmp31_4,
        coeffs_5_load_cast,
        cmp31_5,
        coeffs_6_load_cast,
        cmp31_6,
        coeffs_7_load_cast,
        icmp7,
        coeffs_8_load_cast,
        cmp31_8,
        coeffs_9_load_cast,
        cmp31_9,
        coeffs_10_load_cast,
        cmp31_10,
        coeffs_11_load_cast,
        cmp31_11,
        coeffs_12_load_cast,
        cmp31_12,
        coeffs_13_load_cast,
        cmp31_13,
        coeffs_14_load_cast,
        cmp31_14,
        coeffs_15_load_cast,
        icmp10,
        coeffs_16_load_cast,
        cmp31_16,
        coeffs_17_load_cast,
        cmp31_17,
        coeffs_18_load_cast,
        cmp31_18,
        coeffs_19_load_cast,
        cmp31_19,
        coeffs_20_load_cast,
        cmp31_20,
        coeffs_21_load_cast,
        cmp31_21,
        coeffs_22_load_cast,
        cmp31_22,
        coeffs_23_load_cast,
        cmp31_23,
        coeffs_24_load_cast,
        cmp31_24,
        coeffs_25_load_cast,
        cmp31_25,
        coeffs_26_load_cast,
        cmp31_26,
        coeffs_27_load_cast,
        cmp31_27,
        coeffs_28_load_cast,
        cmp31_28,
        coeffs_29_load_cast,
        cmp31_29,
        coeffs_30_load_cast,
        cmp31_30,
        coeffs_31_load_cast,
        empty,
        sext_ln44,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_stream_TVALID;
input   out_stream_TREADY;
input  [31:0] select_ln44_1;
input  [31:0] in_stream_TDATA;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;
input  [15:0] coeffs_0_load_cast;
input  [15:0] coeffs_1_load_cast;
input  [0:0] icmp;
input  [15:0] coeffs_2_load_cast;
input  [0:0] cmp31_2;
input  [15:0] coeffs_3_load_cast;
input  [0:0] icmp4;
input  [15:0] coeffs_4_load_cast;
input  [0:0] cmp31_4;
input  [15:0] coeffs_5_load_cast;
input  [0:0] cmp31_5;
input  [15:0] coeffs_6_load_cast;
input  [0:0] cmp31_6;
input  [15:0] coeffs_7_load_cast;
input  [0:0] icmp7;
input  [15:0] coeffs_8_load_cast;
input  [0:0] cmp31_8;
input  [15:0] coeffs_9_load_cast;
input  [0:0] cmp31_9;
input  [15:0] coeffs_10_load_cast;
input  [0:0] cmp31_10;
input  [15:0] coeffs_11_load_cast;
input  [0:0] cmp31_11;
input  [15:0] coeffs_12_load_cast;
input  [0:0] cmp31_12;
input  [15:0] coeffs_13_load_cast;
input  [0:0] cmp31_13;
input  [15:0] coeffs_14_load_cast;
input  [0:0] cmp31_14;
input  [15:0] coeffs_15_load_cast;
input  [0:0] icmp10;
input  [15:0] coeffs_16_load_cast;
input  [0:0] cmp31_16;
input  [15:0] coeffs_17_load_cast;
input  [0:0] cmp31_17;
input  [15:0] coeffs_18_load_cast;
input  [0:0] cmp31_18;
input  [15:0] coeffs_19_load_cast;
input  [0:0] cmp31_19;
input  [15:0] coeffs_20_load_cast;
input  [0:0] cmp31_20;
input  [15:0] coeffs_21_load_cast;
input  [0:0] cmp31_21;
input  [15:0] coeffs_22_load_cast;
input  [0:0] cmp31_22;
input  [15:0] coeffs_23_load_cast;
input  [0:0] cmp31_23;
input  [15:0] coeffs_24_load_cast;
input  [0:0] cmp31_24;
input  [15:0] coeffs_25_load_cast;
input  [0:0] cmp31_25;
input  [15:0] coeffs_26_load_cast;
input  [0:0] cmp31_26;
input  [15:0] coeffs_27_load_cast;
input  [0:0] cmp31_27;
input  [15:0] coeffs_28_load_cast;
input  [0:0] cmp31_28;
input  [15:0] coeffs_29_load_cast;
input  [0:0] cmp31_29;
input  [15:0] coeffs_30_load_cast;
input  [0:0] cmp31_30;
input  [15:0] coeffs_31_load_cast;
input  [0:0] empty;
input  [10:0] sext_ln44;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;

reg ap_idle;
reg in_stream_TREADY;
reg out_stream_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_enable_reg_pp0_iter33;
reg    ap_enable_reg_pp0_iter34;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln44_fu_1047_p2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state35_pp0_stage0_iter34;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    out_stream_TDATA_blk_n;
reg    ap_block_pp0_stage0_11001;
wire  signed [31:0] sext_ln44_cast_fu_746_p1;
reg  signed [31:0] sext_ln44_cast_reg_2179;
wire  signed [31:0] coeffs_31_load_cast_cast_fu_750_p1;
reg  signed [31:0] coeffs_31_load_cast_cast_reg_2184;
wire  signed [31:0] coeffs_30_load_cast_cast_fu_754_p1;
reg  signed [31:0] coeffs_30_load_cast_cast_reg_2189;
wire  signed [31:0] coeffs_29_load_cast_cast_fu_758_p1;
reg  signed [31:0] coeffs_29_load_cast_cast_reg_2194;
wire  signed [31:0] coeffs_28_load_cast_cast_fu_762_p1;
reg  signed [31:0] coeffs_28_load_cast_cast_reg_2199;
wire  signed [31:0] coeffs_27_load_cast_cast_fu_766_p1;
reg  signed [31:0] coeffs_27_load_cast_cast_reg_2204;
wire  signed [31:0] coeffs_26_load_cast_cast_fu_770_p1;
reg  signed [31:0] coeffs_26_load_cast_cast_reg_2209;
wire  signed [31:0] coeffs_25_load_cast_cast_fu_774_p1;
reg  signed [31:0] coeffs_25_load_cast_cast_reg_2214;
wire  signed [31:0] coeffs_24_load_cast_cast_fu_778_p1;
reg  signed [31:0] coeffs_24_load_cast_cast_reg_2219;
wire  signed [31:0] coeffs_23_load_cast_cast_fu_782_p1;
reg  signed [31:0] coeffs_23_load_cast_cast_reg_2224;
wire  signed [31:0] coeffs_22_load_cast_cast_fu_786_p1;
reg  signed [31:0] coeffs_22_load_cast_cast_reg_2229;
wire  signed [31:0] coeffs_21_load_cast_cast_fu_790_p1;
reg  signed [31:0] coeffs_21_load_cast_cast_reg_2234;
wire  signed [31:0] coeffs_20_load_cast_cast_fu_794_p1;
reg  signed [31:0] coeffs_20_load_cast_cast_reg_2239;
wire  signed [31:0] coeffs_19_load_cast_cast_fu_798_p1;
reg  signed [31:0] coeffs_19_load_cast_cast_reg_2244;
wire  signed [31:0] coeffs_18_load_cast_cast_fu_802_p1;
reg  signed [31:0] coeffs_18_load_cast_cast_reg_2249;
wire  signed [31:0] coeffs_17_load_cast_cast_fu_806_p1;
reg  signed [31:0] coeffs_17_load_cast_cast_reg_2254;
wire  signed [31:0] coeffs_16_load_cast_cast_fu_810_p1;
reg  signed [31:0] coeffs_16_load_cast_cast_reg_2259;
wire  signed [31:0] coeffs_15_load_cast_cast_fu_814_p1;
reg  signed [31:0] coeffs_15_load_cast_cast_reg_2264;
wire  signed [31:0] coeffs_14_load_cast_cast_fu_818_p1;
reg  signed [31:0] coeffs_14_load_cast_cast_reg_2269;
wire  signed [31:0] coeffs_13_load_cast_cast_fu_822_p1;
reg  signed [31:0] coeffs_13_load_cast_cast_reg_2274;
wire  signed [31:0] coeffs_12_load_cast_cast_fu_826_p1;
reg  signed [31:0] coeffs_12_load_cast_cast_reg_2279;
wire  signed [31:0] coeffs_11_load_cast_cast_fu_830_p1;
reg  signed [31:0] coeffs_11_load_cast_cast_reg_2284;
wire  signed [31:0] coeffs_10_load_cast_cast_fu_834_p1;
reg  signed [31:0] coeffs_10_load_cast_cast_reg_2289;
wire  signed [31:0] coeffs_9_load_cast_cast_fu_838_p1;
reg  signed [31:0] coeffs_9_load_cast_cast_reg_2294;
wire  signed [31:0] coeffs_8_load_cast_cast_fu_842_p1;
reg  signed [31:0] coeffs_8_load_cast_cast_reg_2299;
wire  signed [31:0] coeffs_7_load_cast_cast_fu_846_p1;
reg  signed [31:0] coeffs_7_load_cast_cast_reg_2304;
wire  signed [31:0] coeffs_6_load_cast_cast_fu_850_p1;
reg  signed [31:0] coeffs_6_load_cast_cast_reg_2309;
wire  signed [31:0] coeffs_5_load_cast_cast_fu_854_p1;
reg  signed [31:0] coeffs_5_load_cast_cast_reg_2314;
wire  signed [31:0] coeffs_4_load_cast_cast_fu_858_p1;
reg  signed [31:0] coeffs_4_load_cast_cast_reg_2319;
wire  signed [31:0] coeffs_3_load_cast_cast_fu_862_p1;
reg  signed [31:0] coeffs_3_load_cast_cast_reg_2324;
wire  signed [31:0] coeffs_2_load_cast_cast_fu_866_p1;
reg  signed [31:0] coeffs_2_load_cast_cast_reg_2329;
wire  signed [31:0] coeffs_1_load_cast_cast_fu_870_p1;
reg  signed [31:0] coeffs_1_load_cast_cast_reg_2334;
wire  signed [31:0] coeffs_0_load_cast_cast_fu_874_p1;
reg  signed [31:0] coeffs_0_load_cast_cast_reg_2339;
reg  signed [15:0] p_0_0_097_3039_load_reg_2344;
reg   [0:0] icmp_ln44_reg_2350;
reg   [0:0] icmp_ln44_reg_2350_pp0_iter2_reg;
reg   [0:0] icmp_ln44_reg_2350_pp0_iter3_reg;
reg   [0:0] icmp_ln44_reg_2350_pp0_iter4_reg;
reg   [0:0] icmp_ln44_reg_2350_pp0_iter5_reg;
reg   [0:0] icmp_ln44_reg_2350_pp0_iter6_reg;
reg   [0:0] icmp_ln44_reg_2350_pp0_iter7_reg;
reg   [0:0] icmp_ln44_reg_2350_pp0_iter8_reg;
reg   [0:0] icmp_ln44_reg_2350_pp0_iter9_reg;
reg   [0:0] icmp_ln44_reg_2350_pp0_iter10_reg;
reg   [0:0] icmp_ln44_reg_2350_pp0_iter11_reg;
reg   [0:0] icmp_ln44_reg_2350_pp0_iter12_reg;
reg   [0:0] icmp_ln44_reg_2350_pp0_iter13_reg;
reg   [0:0] icmp_ln44_reg_2350_pp0_iter14_reg;
reg   [0:0] icmp_ln44_reg_2350_pp0_iter15_reg;
reg   [0:0] icmp_ln44_reg_2350_pp0_iter16_reg;
reg   [0:0] icmp_ln44_reg_2350_pp0_iter17_reg;
reg   [0:0] icmp_ln44_reg_2350_pp0_iter18_reg;
reg   [0:0] icmp_ln44_reg_2350_pp0_iter19_reg;
reg   [0:0] icmp_ln44_reg_2350_pp0_iter20_reg;
reg   [0:0] icmp_ln44_reg_2350_pp0_iter21_reg;
reg   [0:0] icmp_ln44_reg_2350_pp0_iter22_reg;
reg   [0:0] icmp_ln44_reg_2350_pp0_iter23_reg;
reg   [0:0] icmp_ln44_reg_2350_pp0_iter24_reg;
reg   [0:0] icmp_ln44_reg_2350_pp0_iter25_reg;
reg   [0:0] icmp_ln44_reg_2350_pp0_iter26_reg;
reg   [0:0] icmp_ln44_reg_2350_pp0_iter27_reg;
reg   [0:0] icmp_ln44_reg_2350_pp0_iter28_reg;
wire  signed [15:0] x_fu_1062_p1;
reg  signed [15:0] x_reg_2354;
wire   [0:0] out_word_last_fu_1070_p2;
reg   [0:0] out_word_last_reg_2364;
reg   [0:0] out_word_last_reg_2364_pp0_iter2_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter3_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter4_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter5_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter6_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter7_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter8_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter9_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter10_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter11_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter12_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter13_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter14_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter15_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter16_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter17_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter18_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter19_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter20_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter21_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter22_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter23_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter24_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter25_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter26_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter27_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter28_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter29_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter30_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter31_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter32_reg;
reg   [0:0] out_word_last_reg_2364_pp0_iter33_reg;
reg  signed [15:0] p_0_0_097_2938_load_reg_2369;
wire   [31:0] acc_fu_1096_p2;
reg  signed [31:0] acc_reg_2375;
reg   [31:0] acc_reg_2375_pp0_iter3_reg;
reg  signed [15:0] p_0_0_097_2837_load_reg_2386;
reg  signed [15:0] p_0_0_097_2736_load_reg_2397;
wire   [31:0] acc_2_fu_1121_p3;
reg   [31:0] acc_2_reg_2403;
reg  signed [15:0] p_0_0_097_2635_load_reg_2414;
wire   [31:0] acc_4_fu_1136_p3;
reg   [31:0] acc_4_reg_2420;
reg  signed [15:0] p_0_0_097_2534_load_reg_2431;
wire   [31:0] acc_6_fu_1151_p3;
reg   [31:0] acc_6_reg_2437;
reg  signed [15:0] p_0_0_097_2433_load_reg_2448;
wire   [31:0] acc_8_fu_1166_p3;
reg   [31:0] acc_8_reg_2454;
reg  signed [15:0] p_0_0_097_2332_load_reg_2465;
wire   [31:0] acc_10_fu_1181_p3;
reg   [31:0] acc_10_reg_2471;
reg  signed [15:0] p_0_0_097_2231_load_reg_2482;
wire   [31:0] acc_12_fu_1196_p3;
reg   [31:0] acc_12_reg_2488;
reg  signed [15:0] p_0_0_097_2130_load_reg_2499;
wire   [31:0] acc_14_fu_1211_p3;
reg   [31:0] acc_14_reg_2505;
reg  signed [15:0] p_0_0_097_2029_load_reg_2516;
wire   [31:0] acc_16_fu_1226_p3;
reg   [31:0] acc_16_reg_2522;
reg  signed [15:0] p_0_0_097_1928_load_reg_2533;
wire   [31:0] acc_18_fu_1241_p3;
reg   [31:0] acc_18_reg_2539;
reg  signed [15:0] p_0_0_097_1827_load_reg_2550;
wire   [31:0] acc_20_fu_1256_p3;
reg   [31:0] acc_20_reg_2556;
reg  signed [15:0] p_0_0_097_1726_load_reg_2567;
wire   [31:0] acc_22_fu_1271_p3;
reg   [31:0] acc_22_reg_2573;
reg  signed [15:0] p_0_0_097_1625_load_reg_2584;
wire   [31:0] acc_24_fu_1286_p3;
reg   [31:0] acc_24_reg_2590;
reg  signed [15:0] p_0_0_097_1524_load_reg_2601;
wire   [31:0] acc_26_fu_1301_p3;
reg   [31:0] acc_26_reg_2607;
reg  signed [15:0] p_0_0_097_1423_load_reg_2618;
wire   [31:0] acc_28_fu_1316_p3;
reg   [31:0] acc_28_reg_2624;
reg  signed [15:0] p_0_0_097_1322_load_reg_2635;
wire   [31:0] acc_30_fu_1331_p3;
reg   [31:0] acc_30_reg_2641;
reg  signed [15:0] p_0_0_097_1221_load_reg_2652;
wire   [31:0] acc_32_fu_1346_p3;
reg   [31:0] acc_32_reg_2658;
reg  signed [15:0] p_0_0_097_1120_load_reg_2669;
wire   [31:0] acc_34_fu_1361_p3;
reg   [31:0] acc_34_reg_2675;
reg  signed [15:0] p_0_0_097_1019_load_reg_2686;
wire   [31:0] acc_36_fu_1376_p3;
reg   [31:0] acc_36_reg_2692;
reg  signed [15:0] p_0_0_097_918_load_reg_2703;
wire   [31:0] acc_38_fu_1391_p3;
reg   [31:0] acc_38_reg_2709;
reg  signed [15:0] p_0_0_097_817_load_reg_2720;
wire   [31:0] acc_40_fu_1406_p3;
reg   [31:0] acc_40_reg_2726;
reg  signed [15:0] p_0_0_097_716_load_reg_2737;
wire   [31:0] acc_42_fu_1421_p3;
reg   [31:0] acc_42_reg_2743;
reg  signed [15:0] p_0_0_097_615_load_reg_2754;
wire   [31:0] acc_44_fu_1436_p3;
reg   [31:0] acc_44_reg_2760;
reg  signed [15:0] p_0_0_097_514_load_reg_2771;
wire   [31:0] acc_46_fu_1451_p3;
reg   [31:0] acc_46_reg_2777;
reg  signed [15:0] p_0_0_097_413_load_reg_2788;
wire   [31:0] acc_48_fu_1466_p3;
reg   [31:0] acc_48_reg_2794;
reg  signed [15:0] p_0_0_097_312_load_reg_2805;
wire   [31:0] acc_50_fu_1481_p3;
reg   [31:0] acc_50_reg_2811;
reg  signed [15:0] p_0_0_097_211_load_reg_2822;
reg  signed [15:0] p_0_0_097_211_load_reg_2822_pp0_iter30_reg;
wire   [31:0] acc_52_fu_1496_p3;
reg   [31:0] acc_52_reg_2828;
wire   [31:0] acc_54_fu_1508_p3;
reg   [31:0] acc_54_reg_2839;
wire   [31:0] acc_56_fu_1519_p3;
reg   [31:0] acc_56_reg_2850;
wire   [31:0] acc_58_fu_1532_p3;
reg   [31:0] acc_58_reg_2861;
wire   [31:0] acc_60_fu_1537_p3;
reg   [31:0] acc_60_reg_2867;
reg    ap_condition_exit_pp0_iter29_stage0;
reg   [31:0] n_fu_198;
wire   [31:0] n_1_fu_1052_p2;
wire    ap_loop_init;
reg  signed [15:0] p_0_0_097_110_fu_202;
reg   [15:0] p_0_0_097_211_fu_206;
reg   [15:0] p_0_0_097_312_fu_210;
reg   [15:0] p_0_0_097_413_fu_214;
reg   [15:0] p_0_0_097_514_fu_218;
reg   [15:0] p_0_0_097_615_fu_222;
reg   [15:0] p_0_0_097_716_fu_226;
reg   [15:0] p_0_0_097_817_fu_230;
reg   [15:0] p_0_0_097_918_fu_234;
reg   [15:0] p_0_0_097_1019_fu_238;
reg   [15:0] p_0_0_097_1120_fu_242;
reg   [15:0] p_0_0_097_1221_fu_246;
reg   [15:0] p_0_0_097_1322_fu_250;
reg   [15:0] p_0_0_097_1423_fu_254;
reg   [15:0] p_0_0_097_1524_fu_258;
reg   [15:0] p_0_0_097_1625_fu_262;
reg   [15:0] p_0_0_097_1726_fu_266;
reg   [15:0] p_0_0_097_1827_fu_270;
reg   [15:0] p_0_0_097_1928_fu_274;
reg   [15:0] p_0_0_097_2029_fu_278;
reg   [15:0] p_0_0_097_2130_fu_282;
reg   [15:0] p_0_0_097_2231_fu_286;
reg   [15:0] p_0_0_097_2332_fu_290;
reg   [15:0] p_0_0_097_2433_fu_294;
reg   [15:0] p_0_0_097_2534_fu_298;
reg   [15:0] p_0_0_097_2635_fu_302;
reg   [15:0] p_0_0_097_2736_fu_306;
reg   [15:0] p_0_0_097_2837_fu_310;
reg   [15:0] p_0_0_097_2938_fu_314;
reg   [15:0] p_0_0_097_3039_fu_318;
reg  signed [15:0] p_0_0_097_3040_fu_322;
reg    ap_block_pp0_stage0_01001;
wire  signed [15:0] acc_fu_1096_p1;
wire  signed [31:0] grp_fu_1548_p3;
wire  signed [31:0] acc_4_fu_1136_p1;
wire   [31:0] grp_fu_1555_p3;
wire  signed [31:0] acc_6_fu_1151_p1;
wire   [31:0] grp_fu_1563_p3;
wire  signed [31:0] acc_8_fu_1166_p1;
wire   [31:0] grp_fu_1571_p3;
wire  signed [31:0] acc_10_fu_1181_p1;
wire   [31:0] grp_fu_1579_p3;
wire  signed [31:0] acc_12_fu_1196_p1;
wire   [31:0] grp_fu_1587_p3;
wire  signed [31:0] acc_14_fu_1211_p1;
wire   [31:0] grp_fu_1595_p3;
wire  signed [31:0] acc_16_fu_1226_p1;
wire   [31:0] grp_fu_1603_p3;
wire  signed [31:0] acc_18_fu_1241_p1;
wire   [31:0] grp_fu_1611_p3;
wire  signed [31:0] acc_20_fu_1256_p1;
wire   [31:0] grp_fu_1619_p3;
wire  signed [31:0] acc_22_fu_1271_p1;
wire   [31:0] grp_fu_1627_p3;
wire  signed [31:0] acc_24_fu_1286_p1;
wire   [31:0] grp_fu_1635_p3;
wire  signed [31:0] acc_26_fu_1301_p1;
wire   [31:0] grp_fu_1643_p3;
wire  signed [31:0] acc_28_fu_1316_p1;
wire   [31:0] grp_fu_1651_p3;
wire  signed [31:0] acc_30_fu_1331_p1;
wire   [31:0] grp_fu_1659_p3;
wire  signed [31:0] acc_32_fu_1346_p1;
wire   [31:0] grp_fu_1667_p3;
wire  signed [31:0] acc_34_fu_1361_p1;
wire   [31:0] grp_fu_1675_p3;
wire  signed [31:0] acc_36_fu_1376_p1;
wire   [31:0] grp_fu_1683_p3;
wire  signed [31:0] acc_38_fu_1391_p1;
wire   [31:0] grp_fu_1691_p3;
wire  signed [31:0] acc_40_fu_1406_p1;
wire   [31:0] grp_fu_1699_p3;
wire  signed [31:0] acc_42_fu_1421_p1;
wire   [31:0] grp_fu_1707_p3;
wire  signed [31:0] acc_44_fu_1436_p1;
wire   [31:0] grp_fu_1715_p3;
wire  signed [31:0] acc_46_fu_1451_p1;
wire   [31:0] grp_fu_1723_p3;
wire  signed [31:0] acc_48_fu_1466_p1;
wire   [31:0] grp_fu_1731_p3;
wire  signed [31:0] acc_50_fu_1481_p1;
wire   [31:0] grp_fu_1739_p3;
wire  signed [31:0] acc_52_fu_1496_p1;
wire   [31:0] grp_fu_1747_p3;
wire  signed [31:0] acc_54_fu_1508_p1;
wire   [31:0] grp_fu_1755_p3;
wire  signed [31:0] acc_56_fu_1519_p1;
wire   [31:0] grp_fu_1763_p3;
wire  signed [31:0] acc_58_fu_1532_p1;
wire   [31:0] grp_fu_1771_p3;
wire  signed [31:0] acc_60_fu_1537_p1;
wire   [31:0] grp_fu_1779_p3;
wire  signed [31:0] acc_63_fu_1542_p1;
wire   [31:0] grp_fu_1787_p3;
wire  signed [15:0] grp_fu_1548_p1;
wire  signed [15:0] grp_fu_1555_p1;
wire   [31:0] grp_fu_1555_p2;
wire  signed [15:0] grp_fu_1563_p1;
wire   [31:0] grp_fu_1563_p2;
wire  signed [15:0] grp_fu_1571_p1;
wire   [31:0] grp_fu_1571_p2;
wire  signed [15:0] grp_fu_1579_p1;
wire   [31:0] grp_fu_1579_p2;
wire  signed [15:0] grp_fu_1587_p1;
wire   [31:0] grp_fu_1587_p2;
wire  signed [15:0] grp_fu_1595_p1;
wire   [31:0] grp_fu_1595_p2;
wire  signed [15:0] grp_fu_1603_p1;
wire   [31:0] grp_fu_1603_p2;
wire  signed [15:0] grp_fu_1611_p1;
wire   [31:0] grp_fu_1611_p2;
wire  signed [15:0] grp_fu_1619_p1;
wire   [31:0] grp_fu_1619_p2;
wire  signed [15:0] grp_fu_1627_p1;
wire   [31:0] grp_fu_1627_p2;
wire  signed [15:0] grp_fu_1635_p1;
wire   [31:0] grp_fu_1635_p2;
wire  signed [15:0] grp_fu_1643_p1;
wire   [31:0] grp_fu_1643_p2;
wire  signed [15:0] grp_fu_1651_p1;
wire   [31:0] grp_fu_1651_p2;
wire  signed [15:0] grp_fu_1659_p1;
wire   [31:0] grp_fu_1659_p2;
wire  signed [15:0] grp_fu_1667_p1;
wire   [31:0] grp_fu_1667_p2;
wire  signed [15:0] grp_fu_1675_p1;
wire   [31:0] grp_fu_1675_p2;
wire  signed [15:0] grp_fu_1683_p1;
wire   [31:0] grp_fu_1683_p2;
wire  signed [15:0] grp_fu_1691_p1;
wire   [31:0] grp_fu_1691_p2;
wire  signed [15:0] grp_fu_1699_p1;
wire   [31:0] grp_fu_1699_p2;
wire  signed [15:0] grp_fu_1707_p1;
wire   [31:0] grp_fu_1707_p2;
wire  signed [15:0] grp_fu_1715_p1;
wire   [31:0] grp_fu_1715_p2;
wire  signed [15:0] grp_fu_1723_p1;
wire   [31:0] grp_fu_1723_p2;
wire  signed [15:0] grp_fu_1731_p1;
wire   [31:0] grp_fu_1731_p2;
wire  signed [15:0] grp_fu_1739_p1;
wire   [31:0] grp_fu_1739_p2;
wire  signed [15:0] grp_fu_1747_p1;
wire   [31:0] grp_fu_1747_p2;
wire  signed [15:0] grp_fu_1755_p1;
wire   [31:0] grp_fu_1755_p2;
wire  signed [15:0] grp_fu_1763_p1;
wire   [31:0] grp_fu_1763_p2;
wire  signed [15:0] grp_fu_1771_p1;
wire   [31:0] grp_fu_1771_p2;
wire  signed [15:0] grp_fu_1779_p1;
wire   [31:0] grp_fu_1779_p2;
wire  signed [15:0] grp_fu_1787_p1;
wire   [31:0] grp_fu_1787_p2;
reg    grp_fu_1548_ce;
reg    grp_fu_1555_ce;
reg    grp_fu_1563_ce;
reg    grp_fu_1571_ce;
reg    grp_fu_1579_ce;
reg    grp_fu_1587_ce;
reg    grp_fu_1595_ce;
reg    grp_fu_1603_ce;
reg    grp_fu_1611_ce;
reg    grp_fu_1619_ce;
reg    grp_fu_1627_ce;
reg    grp_fu_1635_ce;
reg    grp_fu_1643_ce;
reg    grp_fu_1651_ce;
reg    grp_fu_1659_ce;
reg    grp_fu_1667_ce;
reg    grp_fu_1675_ce;
reg    grp_fu_1683_ce;
reg    grp_fu_1691_ce;
reg    grp_fu_1699_ce;
reg    grp_fu_1707_ce;
reg    grp_fu_1715_ce;
reg    grp_fu_1723_ce;
reg    grp_fu_1731_ce;
reg    grp_fu_1739_ce;
reg    grp_fu_1747_ce;
reg    grp_fu_1755_ce;
reg    grp_fu_1763_ce;
reg    grp_fu_1771_ce;
reg    grp_fu_1779_ce;
reg    grp_fu_1787_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg    ap_loop_exit_ready_pp0_iter26_reg;
reg    ap_loop_exit_ready_pp0_iter27_reg;
reg    ap_loop_exit_ready_pp0_iter28_reg;
reg    ap_loop_exit_ready_pp0_iter29_reg;
reg    ap_loop_exit_ready_pp0_iter30_reg;
reg    ap_loop_exit_ready_pp0_iter31_reg;
reg    ap_loop_exit_ready_pp0_iter32_reg;
reg    ap_loop_exit_ready_pp0_iter33_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 ap_enable_reg_pp0_iter33 = 1'b0;
#0 ap_enable_reg_pp0_iter34 = 1'b0;
#0 n_fu_198 = 32'd0;
#0 p_0_0_097_110_fu_202 = 16'd0;
#0 p_0_0_097_211_fu_206 = 16'd0;
#0 p_0_0_097_312_fu_210 = 16'd0;
#0 p_0_0_097_413_fu_214 = 16'd0;
#0 p_0_0_097_514_fu_218 = 16'd0;
#0 p_0_0_097_615_fu_222 = 16'd0;
#0 p_0_0_097_716_fu_226 = 16'd0;
#0 p_0_0_097_817_fu_230 = 16'd0;
#0 p_0_0_097_918_fu_234 = 16'd0;
#0 p_0_0_097_1019_fu_238 = 16'd0;
#0 p_0_0_097_1120_fu_242 = 16'd0;
#0 p_0_0_097_1221_fu_246 = 16'd0;
#0 p_0_0_097_1322_fu_250 = 16'd0;
#0 p_0_0_097_1423_fu_254 = 16'd0;
#0 p_0_0_097_1524_fu_258 = 16'd0;
#0 p_0_0_097_1625_fu_262 = 16'd0;
#0 p_0_0_097_1726_fu_266 = 16'd0;
#0 p_0_0_097_1827_fu_270 = 16'd0;
#0 p_0_0_097_1928_fu_274 = 16'd0;
#0 p_0_0_097_2029_fu_278 = 16'd0;
#0 p_0_0_097_2130_fu_282 = 16'd0;
#0 p_0_0_097_2231_fu_286 = 16'd0;
#0 p_0_0_097_2332_fu_290 = 16'd0;
#0 p_0_0_097_2433_fu_294 = 16'd0;
#0 p_0_0_097_2534_fu_298 = 16'd0;
#0 p_0_0_097_2635_fu_302 = 16'd0;
#0 p_0_0_097_2736_fu_306 = 16'd0;
#0 p_0_0_097_2837_fu_310 = 16'd0;
#0 p_0_0_097_2938_fu_314 = 16'd0;
#0 p_0_0_097_3039_fu_318 = 16'd0;
#0 p_0_0_097_3040_fu_322 = 16'd0;
#0 ap_done_reg = 1'b0;
end

fir_filter_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U1(
    .din0(x_reg_2354),
    .din1(acc_fu_1096_p1),
    .dout(acc_fu_1096_p2)
);

fir_filter_mac_muladd_16s_16s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32s_32_4_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_3040_fu_322),
    .din1(grp_fu_1548_p1),
    .din2(acc_reg_2375),
    .ce(grp_fu_1548_ce),
    .dout(grp_fu_1548_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_3039_load_reg_2344),
    .din1(grp_fu_1555_p1),
    .din2(grp_fu_1555_p2),
    .ce(grp_fu_1555_ce),
    .dout(grp_fu_1555_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_2938_load_reg_2369),
    .din1(grp_fu_1563_p1),
    .din2(grp_fu_1563_p2),
    .ce(grp_fu_1563_ce),
    .dout(grp_fu_1563_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_2837_load_reg_2386),
    .din1(grp_fu_1571_p1),
    .din2(grp_fu_1571_p2),
    .ce(grp_fu_1571_ce),
    .dout(grp_fu_1571_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_2736_load_reg_2397),
    .din1(grp_fu_1579_p1),
    .din2(grp_fu_1579_p2),
    .ce(grp_fu_1579_ce),
    .dout(grp_fu_1579_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_2635_load_reg_2414),
    .din1(grp_fu_1587_p1),
    .din2(grp_fu_1587_p2),
    .ce(grp_fu_1587_ce),
    .dout(grp_fu_1587_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_2534_load_reg_2431),
    .din1(grp_fu_1595_p1),
    .din2(grp_fu_1595_p2),
    .ce(grp_fu_1595_ce),
    .dout(grp_fu_1595_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_2433_load_reg_2448),
    .din1(grp_fu_1603_p1),
    .din2(grp_fu_1603_p2),
    .ce(grp_fu_1603_ce),
    .dout(grp_fu_1603_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_2332_load_reg_2465),
    .din1(grp_fu_1611_p1),
    .din2(grp_fu_1611_p2),
    .ce(grp_fu_1611_ce),
    .dout(grp_fu_1611_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_2231_load_reg_2482),
    .din1(grp_fu_1619_p1),
    .din2(grp_fu_1619_p2),
    .ce(grp_fu_1619_ce),
    .dout(grp_fu_1619_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_2130_load_reg_2499),
    .din1(grp_fu_1627_p1),
    .din2(grp_fu_1627_p2),
    .ce(grp_fu_1627_ce),
    .dout(grp_fu_1627_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_2029_load_reg_2516),
    .din1(grp_fu_1635_p1),
    .din2(grp_fu_1635_p2),
    .ce(grp_fu_1635_ce),
    .dout(grp_fu_1635_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_1928_load_reg_2533),
    .din1(grp_fu_1643_p1),
    .din2(grp_fu_1643_p2),
    .ce(grp_fu_1643_ce),
    .dout(grp_fu_1643_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_1827_load_reg_2550),
    .din1(grp_fu_1651_p1),
    .din2(grp_fu_1651_p2),
    .ce(grp_fu_1651_ce),
    .dout(grp_fu_1651_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_1726_load_reg_2567),
    .din1(grp_fu_1659_p1),
    .din2(grp_fu_1659_p2),
    .ce(grp_fu_1659_ce),
    .dout(grp_fu_1659_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_1625_load_reg_2584),
    .din1(grp_fu_1667_p1),
    .din2(grp_fu_1667_p2),
    .ce(grp_fu_1667_ce),
    .dout(grp_fu_1667_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_1524_load_reg_2601),
    .din1(grp_fu_1675_p1),
    .din2(grp_fu_1675_p2),
    .ce(grp_fu_1675_ce),
    .dout(grp_fu_1675_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_1423_load_reg_2618),
    .din1(grp_fu_1683_p1),
    .din2(grp_fu_1683_p2),
    .ce(grp_fu_1683_ce),
    .dout(grp_fu_1683_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_1322_load_reg_2635),
    .din1(grp_fu_1691_p1),
    .din2(grp_fu_1691_p2),
    .ce(grp_fu_1691_ce),
    .dout(grp_fu_1691_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_1221_load_reg_2652),
    .din1(grp_fu_1699_p1),
    .din2(grp_fu_1699_p2),
    .ce(grp_fu_1699_ce),
    .dout(grp_fu_1699_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_1120_load_reg_2669),
    .din1(grp_fu_1707_p1),
    .din2(grp_fu_1707_p2),
    .ce(grp_fu_1707_ce),
    .dout(grp_fu_1707_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_1019_load_reg_2686),
    .din1(grp_fu_1715_p1),
    .din2(grp_fu_1715_p2),
    .ce(grp_fu_1715_ce),
    .dout(grp_fu_1715_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_918_load_reg_2703),
    .din1(grp_fu_1723_p1),
    .din2(grp_fu_1723_p2),
    .ce(grp_fu_1723_ce),
    .dout(grp_fu_1723_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_817_load_reg_2720),
    .din1(grp_fu_1731_p1),
    .din2(grp_fu_1731_p2),
    .ce(grp_fu_1731_ce),
    .dout(grp_fu_1731_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U26(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_716_load_reg_2737),
    .din1(grp_fu_1739_p1),
    .din2(grp_fu_1739_p2),
    .ce(grp_fu_1739_ce),
    .dout(grp_fu_1739_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_615_load_reg_2754),
    .din1(grp_fu_1747_p1),
    .din2(grp_fu_1747_p2),
    .ce(grp_fu_1747_ce),
    .dout(grp_fu_1747_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_514_load_reg_2771),
    .din1(grp_fu_1755_p1),
    .din2(grp_fu_1755_p2),
    .ce(grp_fu_1755_ce),
    .dout(grp_fu_1755_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U29(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_413_load_reg_2788),
    .din1(grp_fu_1763_p1),
    .din2(grp_fu_1763_p2),
    .ce(grp_fu_1763_ce),
    .dout(grp_fu_1763_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_312_load_reg_2805),
    .din1(grp_fu_1771_p1),
    .din2(grp_fu_1771_p2),
    .ce(grp_fu_1771_ce),
    .dout(grp_fu_1771_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_211_load_reg_2822),
    .din1(grp_fu_1779_p1),
    .din2(grp_fu_1779_p2),
    .ce(grp_fu_1779_ce),
    .dout(grp_fu_1779_p3)
);

fir_filter_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U32(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0_0_097_110_fu_202),
    .din1(grp_fu_1787_p1),
    .din2(grp_fu_1787_p2),
    .ce(grp_fu_1787_ce),
    .dout(grp_fu_1787_p3)
);

fir_filter_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter33_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter29_stage0)) begin
            ap_enable_reg_pp0_iter30 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter33 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter34 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            n_fu_198 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln44_fu_1047_p2 == 1'd0))) begin
            n_fu_198 <= n_1_fu_1052_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_1019_fu_238 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter21 == 1'b1) & (icmp_ln44_reg_2350_pp0_iter20_reg == 1'd0))) begin
            p_0_0_097_1019_fu_238 <= p_0_0_097_1120_load_reg_2669;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_110_fu_202 <= 16'd0;
        end else if ((ap_enable_reg_pp0_iter31 == 1'b1)) begin
            p_0_0_097_110_fu_202 <= p_0_0_097_211_load_reg_2822_pp0_iter30_reg;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_1120_fu_242 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter20 == 1'b1) & (icmp_ln44_reg_2350_pp0_iter19_reg == 1'd0))) begin
            p_0_0_097_1120_fu_242 <= p_0_0_097_1221_load_reg_2652;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_1221_fu_246 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter19 == 1'b1) & (icmp_ln44_reg_2350_pp0_iter18_reg == 1'd0))) begin
            p_0_0_097_1221_fu_246 <= p_0_0_097_1322_load_reg_2635;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_1322_fu_250 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter18 == 1'b1) & (icmp_ln44_reg_2350_pp0_iter17_reg == 1'd0))) begin
            p_0_0_097_1322_fu_250 <= p_0_0_097_1423_load_reg_2618;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_1423_fu_254 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln44_reg_2350_pp0_iter16_reg == 1'd0))) begin
            p_0_0_097_1423_fu_254 <= p_0_0_097_1524_load_reg_2601;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_1524_fu_258 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter16 == 1'b1) & (icmp_ln44_reg_2350_pp0_iter15_reg == 1'd0))) begin
            p_0_0_097_1524_fu_258 <= p_0_0_097_1625_load_reg_2584;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_1625_fu_262 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter15 == 1'b1) & (icmp_ln44_reg_2350_pp0_iter14_reg == 1'd0))) begin
            p_0_0_097_1625_fu_262 <= p_0_0_097_1726_load_reg_2567;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_1726_fu_266 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter14 == 1'b1) & (icmp_ln44_reg_2350_pp0_iter13_reg == 1'd0))) begin
            p_0_0_097_1726_fu_266 <= p_0_0_097_1827_load_reg_2550;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_1827_fu_270 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter13 == 1'b1) & (icmp_ln44_reg_2350_pp0_iter12_reg == 1'd0))) begin
            p_0_0_097_1827_fu_270 <= p_0_0_097_1928_load_reg_2533;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_1928_fu_274 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter12 == 1'b1) & (icmp_ln44_reg_2350_pp0_iter11_reg == 1'd0))) begin
            p_0_0_097_1928_fu_274 <= p_0_0_097_2029_load_reg_2516;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_2029_fu_278 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln44_reg_2350_pp0_iter10_reg == 1'd0))) begin
            p_0_0_097_2029_fu_278 <= p_0_0_097_2130_load_reg_2499;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_211_fu_206 <= 16'd0;
        end else if (((icmp_ln44_reg_2350_pp0_iter28_reg == 1'd0) & (ap_enable_reg_pp0_iter29 == 1'b1))) begin
            p_0_0_097_211_fu_206 <= p_0_0_097_312_load_reg_2805;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_2130_fu_282 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (icmp_ln44_reg_2350_pp0_iter9_reg == 1'd0))) begin
            p_0_0_097_2130_fu_282 <= p_0_0_097_2231_load_reg_2482;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_2231_fu_286 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter9 == 1'b1) & (icmp_ln44_reg_2350_pp0_iter8_reg == 1'd0))) begin
            p_0_0_097_2231_fu_286 <= p_0_0_097_2332_load_reg_2465;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_2332_fu_290 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter8 == 1'b1) & (icmp_ln44_reg_2350_pp0_iter7_reg == 1'd0))) begin
            p_0_0_097_2332_fu_290 <= p_0_0_097_2433_load_reg_2448;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_2433_fu_294 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln44_reg_2350_pp0_iter6_reg == 1'd0))) begin
            p_0_0_097_2433_fu_294 <= p_0_0_097_2534_load_reg_2431;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_2534_fu_298 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln44_reg_2350_pp0_iter5_reg == 1'd0))) begin
            p_0_0_097_2534_fu_298 <= p_0_0_097_2635_load_reg_2414;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_2635_fu_302 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln44_reg_2350_pp0_iter4_reg == 1'd0))) begin
            p_0_0_097_2635_fu_302 <= p_0_0_097_2736_load_reg_2397;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_2736_fu_306 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln44_reg_2350_pp0_iter3_reg == 1'd0))) begin
            p_0_0_097_2736_fu_306 <= p_0_0_097_2837_load_reg_2386;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_2837_fu_310 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln44_reg_2350_pp0_iter2_reg == 1'd0))) begin
            p_0_0_097_2837_fu_310 <= p_0_0_097_2938_load_reg_2369;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_2938_fu_314 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln44_reg_2350 == 1'd0))) begin
            p_0_0_097_2938_fu_314 <= p_0_0_097_3039_load_reg_2344;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_097_3039_fu_318 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln44_fu_1047_p2 == 1'd0))) begin
            p_0_0_097_3039_fu_318 <= p_0_0_097_3040_fu_322;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_097_3040_fu_322 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln44_fu_1047_p2 == 1'd0))) begin
            p_0_0_097_3040_fu_322 <= x_fu_1062_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_312_fu_210 <= 16'd0;
        end else if (((icmp_ln44_reg_2350_pp0_iter27_reg == 1'd0) & (ap_enable_reg_pp0_iter28 == 1'b1))) begin
            p_0_0_097_312_fu_210 <= p_0_0_097_413_load_reg_2788;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_413_fu_214 <= 16'd0;
        end else if (((icmp_ln44_reg_2350_pp0_iter26_reg == 1'd0) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
            p_0_0_097_413_fu_214 <= p_0_0_097_514_load_reg_2771;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_514_fu_218 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter26 == 1'b1) & (icmp_ln44_reg_2350_pp0_iter25_reg == 1'd0))) begin
            p_0_0_097_514_fu_218 <= p_0_0_097_615_load_reg_2754;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_615_fu_222 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter25 == 1'b1) & (icmp_ln44_reg_2350_pp0_iter24_reg == 1'd0))) begin
            p_0_0_097_615_fu_222 <= p_0_0_097_716_load_reg_2737;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_716_fu_226 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter24 == 1'b1) & (icmp_ln44_reg_2350_pp0_iter23_reg == 1'd0))) begin
            p_0_0_097_716_fu_226 <= p_0_0_097_817_load_reg_2720;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_817_fu_230 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter23 == 1'b1) & (icmp_ln44_reg_2350_pp0_iter22_reg == 1'd0))) begin
            p_0_0_097_817_fu_230 <= p_0_0_097_918_load_reg_2703;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_097_918_fu_234 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter22 == 1'b1) & (icmp_ln44_reg_2350_pp0_iter21_reg == 1'd0))) begin
            p_0_0_097_918_fu_234 <= p_0_0_097_1019_load_reg_2686;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        acc_10_reg_2471 <= acc_10_fu_1181_p3;
        acc_12_reg_2488 <= acc_12_fu_1196_p3;
        acc_14_reg_2505 <= acc_14_fu_1211_p3;
        acc_16_reg_2522 <= acc_16_fu_1226_p3;
        acc_18_reg_2539 <= acc_18_fu_1241_p3;
        acc_20_reg_2556 <= acc_20_fu_1256_p3;
        acc_22_reg_2573 <= acc_22_fu_1271_p3;
        acc_24_reg_2590 <= acc_24_fu_1286_p3;
        acc_26_reg_2607 <= acc_26_fu_1301_p3;
        acc_28_reg_2624 <= acc_28_fu_1316_p3;
        acc_2_reg_2403 <= acc_2_fu_1121_p3;
        acc_30_reg_2641 <= acc_30_fu_1331_p3;
        acc_32_reg_2658 <= acc_32_fu_1346_p3;
        acc_34_reg_2675 <= acc_34_fu_1361_p3;
        acc_36_reg_2692 <= acc_36_fu_1376_p3;
        acc_38_reg_2709 <= acc_38_fu_1391_p3;
        acc_40_reg_2726 <= acc_40_fu_1406_p3;
        acc_42_reg_2743 <= acc_42_fu_1421_p3;
        acc_44_reg_2760 <= acc_44_fu_1436_p3;
        acc_46_reg_2777 <= acc_46_fu_1451_p3;
        acc_48_reg_2794 <= acc_48_fu_1466_p3;
        acc_4_reg_2420 <= acc_4_fu_1136_p3;
        acc_50_reg_2811 <= acc_50_fu_1481_p3;
        acc_52_reg_2828 <= acc_52_fu_1496_p3;
        acc_54_reg_2839 <= acc_54_fu_1508_p3;
        acc_56_reg_2850 <= acc_56_fu_1519_p3;
        acc_58_reg_2861 <= acc_58_fu_1532_p3;
        acc_60_reg_2867 <= acc_60_fu_1537_p3;
        acc_6_reg_2437 <= acc_6_fu_1151_p3;
        acc_8_reg_2454 <= acc_8_fu_1166_p3;
        acc_reg_2375 <= acc_fu_1096_p2;
        acc_reg_2375_pp0_iter3_reg <= acc_reg_2375;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
        ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
        ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
        ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
        ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
        ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
        ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
        ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
        ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln44_reg_2350_pp0_iter10_reg <= icmp_ln44_reg_2350_pp0_iter9_reg;
        icmp_ln44_reg_2350_pp0_iter11_reg <= icmp_ln44_reg_2350_pp0_iter10_reg;
        icmp_ln44_reg_2350_pp0_iter12_reg <= icmp_ln44_reg_2350_pp0_iter11_reg;
        icmp_ln44_reg_2350_pp0_iter13_reg <= icmp_ln44_reg_2350_pp0_iter12_reg;
        icmp_ln44_reg_2350_pp0_iter14_reg <= icmp_ln44_reg_2350_pp0_iter13_reg;
        icmp_ln44_reg_2350_pp0_iter15_reg <= icmp_ln44_reg_2350_pp0_iter14_reg;
        icmp_ln44_reg_2350_pp0_iter16_reg <= icmp_ln44_reg_2350_pp0_iter15_reg;
        icmp_ln44_reg_2350_pp0_iter17_reg <= icmp_ln44_reg_2350_pp0_iter16_reg;
        icmp_ln44_reg_2350_pp0_iter18_reg <= icmp_ln44_reg_2350_pp0_iter17_reg;
        icmp_ln44_reg_2350_pp0_iter19_reg <= icmp_ln44_reg_2350_pp0_iter18_reg;
        icmp_ln44_reg_2350_pp0_iter20_reg <= icmp_ln44_reg_2350_pp0_iter19_reg;
        icmp_ln44_reg_2350_pp0_iter21_reg <= icmp_ln44_reg_2350_pp0_iter20_reg;
        icmp_ln44_reg_2350_pp0_iter22_reg <= icmp_ln44_reg_2350_pp0_iter21_reg;
        icmp_ln44_reg_2350_pp0_iter23_reg <= icmp_ln44_reg_2350_pp0_iter22_reg;
        icmp_ln44_reg_2350_pp0_iter24_reg <= icmp_ln44_reg_2350_pp0_iter23_reg;
        icmp_ln44_reg_2350_pp0_iter25_reg <= icmp_ln44_reg_2350_pp0_iter24_reg;
        icmp_ln44_reg_2350_pp0_iter26_reg <= icmp_ln44_reg_2350_pp0_iter25_reg;
        icmp_ln44_reg_2350_pp0_iter27_reg <= icmp_ln44_reg_2350_pp0_iter26_reg;
        icmp_ln44_reg_2350_pp0_iter28_reg <= icmp_ln44_reg_2350_pp0_iter27_reg;
        icmp_ln44_reg_2350_pp0_iter2_reg <= icmp_ln44_reg_2350;
        icmp_ln44_reg_2350_pp0_iter3_reg <= icmp_ln44_reg_2350_pp0_iter2_reg;
        icmp_ln44_reg_2350_pp0_iter4_reg <= icmp_ln44_reg_2350_pp0_iter3_reg;
        icmp_ln44_reg_2350_pp0_iter5_reg <= icmp_ln44_reg_2350_pp0_iter4_reg;
        icmp_ln44_reg_2350_pp0_iter6_reg <= icmp_ln44_reg_2350_pp0_iter5_reg;
        icmp_ln44_reg_2350_pp0_iter7_reg <= icmp_ln44_reg_2350_pp0_iter6_reg;
        icmp_ln44_reg_2350_pp0_iter8_reg <= icmp_ln44_reg_2350_pp0_iter7_reg;
        icmp_ln44_reg_2350_pp0_iter9_reg <= icmp_ln44_reg_2350_pp0_iter8_reg;
        out_word_last_reg_2364_pp0_iter10_reg <= out_word_last_reg_2364_pp0_iter9_reg;
        out_word_last_reg_2364_pp0_iter11_reg <= out_word_last_reg_2364_pp0_iter10_reg;
        out_word_last_reg_2364_pp0_iter12_reg <= out_word_last_reg_2364_pp0_iter11_reg;
        out_word_last_reg_2364_pp0_iter13_reg <= out_word_last_reg_2364_pp0_iter12_reg;
        out_word_last_reg_2364_pp0_iter14_reg <= out_word_last_reg_2364_pp0_iter13_reg;
        out_word_last_reg_2364_pp0_iter15_reg <= out_word_last_reg_2364_pp0_iter14_reg;
        out_word_last_reg_2364_pp0_iter16_reg <= out_word_last_reg_2364_pp0_iter15_reg;
        out_word_last_reg_2364_pp0_iter17_reg <= out_word_last_reg_2364_pp0_iter16_reg;
        out_word_last_reg_2364_pp0_iter18_reg <= out_word_last_reg_2364_pp0_iter17_reg;
        out_word_last_reg_2364_pp0_iter19_reg <= out_word_last_reg_2364_pp0_iter18_reg;
        out_word_last_reg_2364_pp0_iter20_reg <= out_word_last_reg_2364_pp0_iter19_reg;
        out_word_last_reg_2364_pp0_iter21_reg <= out_word_last_reg_2364_pp0_iter20_reg;
        out_word_last_reg_2364_pp0_iter22_reg <= out_word_last_reg_2364_pp0_iter21_reg;
        out_word_last_reg_2364_pp0_iter23_reg <= out_word_last_reg_2364_pp0_iter22_reg;
        out_word_last_reg_2364_pp0_iter24_reg <= out_word_last_reg_2364_pp0_iter23_reg;
        out_word_last_reg_2364_pp0_iter25_reg <= out_word_last_reg_2364_pp0_iter24_reg;
        out_word_last_reg_2364_pp0_iter26_reg <= out_word_last_reg_2364_pp0_iter25_reg;
        out_word_last_reg_2364_pp0_iter27_reg <= out_word_last_reg_2364_pp0_iter26_reg;
        out_word_last_reg_2364_pp0_iter28_reg <= out_word_last_reg_2364_pp0_iter27_reg;
        out_word_last_reg_2364_pp0_iter29_reg <= out_word_last_reg_2364_pp0_iter28_reg;
        out_word_last_reg_2364_pp0_iter2_reg <= out_word_last_reg_2364;
        out_word_last_reg_2364_pp0_iter30_reg <= out_word_last_reg_2364_pp0_iter29_reg;
        out_word_last_reg_2364_pp0_iter31_reg <= out_word_last_reg_2364_pp0_iter30_reg;
        out_word_last_reg_2364_pp0_iter32_reg <= out_word_last_reg_2364_pp0_iter31_reg;
        out_word_last_reg_2364_pp0_iter33_reg <= out_word_last_reg_2364_pp0_iter32_reg;
        out_word_last_reg_2364_pp0_iter3_reg <= out_word_last_reg_2364_pp0_iter2_reg;
        out_word_last_reg_2364_pp0_iter4_reg <= out_word_last_reg_2364_pp0_iter3_reg;
        out_word_last_reg_2364_pp0_iter5_reg <= out_word_last_reg_2364_pp0_iter4_reg;
        out_word_last_reg_2364_pp0_iter6_reg <= out_word_last_reg_2364_pp0_iter5_reg;
        out_word_last_reg_2364_pp0_iter7_reg <= out_word_last_reg_2364_pp0_iter6_reg;
        out_word_last_reg_2364_pp0_iter8_reg <= out_word_last_reg_2364_pp0_iter7_reg;
        out_word_last_reg_2364_pp0_iter9_reg <= out_word_last_reg_2364_pp0_iter8_reg;
        p_0_0_097_1019_load_reg_2686 <= p_0_0_097_1019_fu_238;
        p_0_0_097_1120_load_reg_2669 <= p_0_0_097_1120_fu_242;
        p_0_0_097_1221_load_reg_2652 <= p_0_0_097_1221_fu_246;
        p_0_0_097_1322_load_reg_2635 <= p_0_0_097_1322_fu_250;
        p_0_0_097_1423_load_reg_2618 <= p_0_0_097_1423_fu_254;
        p_0_0_097_1524_load_reg_2601 <= p_0_0_097_1524_fu_258;
        p_0_0_097_1625_load_reg_2584 <= p_0_0_097_1625_fu_262;
        p_0_0_097_1726_load_reg_2567 <= p_0_0_097_1726_fu_266;
        p_0_0_097_1827_load_reg_2550 <= p_0_0_097_1827_fu_270;
        p_0_0_097_1928_load_reg_2533 <= p_0_0_097_1928_fu_274;
        p_0_0_097_2029_load_reg_2516 <= p_0_0_097_2029_fu_278;
        p_0_0_097_211_load_reg_2822 <= p_0_0_097_211_fu_206;
        p_0_0_097_211_load_reg_2822_pp0_iter30_reg <= p_0_0_097_211_load_reg_2822;
        p_0_0_097_2130_load_reg_2499 <= p_0_0_097_2130_fu_282;
        p_0_0_097_2231_load_reg_2482 <= p_0_0_097_2231_fu_286;
        p_0_0_097_2332_load_reg_2465 <= p_0_0_097_2332_fu_290;
        p_0_0_097_2433_load_reg_2448 <= p_0_0_097_2433_fu_294;
        p_0_0_097_2534_load_reg_2431 <= p_0_0_097_2534_fu_298;
        p_0_0_097_2635_load_reg_2414 <= p_0_0_097_2635_fu_302;
        p_0_0_097_2736_load_reg_2397 <= p_0_0_097_2736_fu_306;
        p_0_0_097_2837_load_reg_2386 <= p_0_0_097_2837_fu_310;
        p_0_0_097_2938_load_reg_2369 <= p_0_0_097_2938_fu_314;
        p_0_0_097_312_load_reg_2805 <= p_0_0_097_312_fu_210;
        p_0_0_097_413_load_reg_2788 <= p_0_0_097_413_fu_214;
        p_0_0_097_514_load_reg_2771 <= p_0_0_097_514_fu_218;
        p_0_0_097_615_load_reg_2754 <= p_0_0_097_615_fu_222;
        p_0_0_097_716_load_reg_2737 <= p_0_0_097_716_fu_226;
        p_0_0_097_817_load_reg_2720 <= p_0_0_097_817_fu_230;
        p_0_0_097_918_load_reg_2703 <= p_0_0_097_918_fu_234;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        coeffs_0_load_cast_cast_reg_2339 <= coeffs_0_load_cast_cast_fu_874_p1;
        coeffs_10_load_cast_cast_reg_2289 <= coeffs_10_load_cast_cast_fu_834_p1;
        coeffs_11_load_cast_cast_reg_2284 <= coeffs_11_load_cast_cast_fu_830_p1;
        coeffs_12_load_cast_cast_reg_2279 <= coeffs_12_load_cast_cast_fu_826_p1;
        coeffs_13_load_cast_cast_reg_2274 <= coeffs_13_load_cast_cast_fu_822_p1;
        coeffs_14_load_cast_cast_reg_2269 <= coeffs_14_load_cast_cast_fu_818_p1;
        coeffs_15_load_cast_cast_reg_2264 <= coeffs_15_load_cast_cast_fu_814_p1;
        coeffs_16_load_cast_cast_reg_2259 <= coeffs_16_load_cast_cast_fu_810_p1;
        coeffs_17_load_cast_cast_reg_2254 <= coeffs_17_load_cast_cast_fu_806_p1;
        coeffs_18_load_cast_cast_reg_2249 <= coeffs_18_load_cast_cast_fu_802_p1;
        coeffs_19_load_cast_cast_reg_2244 <= coeffs_19_load_cast_cast_fu_798_p1;
        coeffs_1_load_cast_cast_reg_2334 <= coeffs_1_load_cast_cast_fu_870_p1;
        coeffs_20_load_cast_cast_reg_2239 <= coeffs_20_load_cast_cast_fu_794_p1;
        coeffs_21_load_cast_cast_reg_2234 <= coeffs_21_load_cast_cast_fu_790_p1;
        coeffs_22_load_cast_cast_reg_2229 <= coeffs_22_load_cast_cast_fu_786_p1;
        coeffs_23_load_cast_cast_reg_2224 <= coeffs_23_load_cast_cast_fu_782_p1;
        coeffs_24_load_cast_cast_reg_2219 <= coeffs_24_load_cast_cast_fu_778_p1;
        coeffs_25_load_cast_cast_reg_2214 <= coeffs_25_load_cast_cast_fu_774_p1;
        coeffs_26_load_cast_cast_reg_2209 <= coeffs_26_load_cast_cast_fu_770_p1;
        coeffs_27_load_cast_cast_reg_2204 <= coeffs_27_load_cast_cast_fu_766_p1;
        coeffs_28_load_cast_cast_reg_2199 <= coeffs_28_load_cast_cast_fu_762_p1;
        coeffs_29_load_cast_cast_reg_2194 <= coeffs_29_load_cast_cast_fu_758_p1;
        coeffs_2_load_cast_cast_reg_2329 <= coeffs_2_load_cast_cast_fu_866_p1;
        coeffs_30_load_cast_cast_reg_2189 <= coeffs_30_load_cast_cast_fu_754_p1;
        coeffs_31_load_cast_cast_reg_2184 <= coeffs_31_load_cast_cast_fu_750_p1;
        coeffs_3_load_cast_cast_reg_2324 <= coeffs_3_load_cast_cast_fu_862_p1;
        coeffs_4_load_cast_cast_reg_2319 <= coeffs_4_load_cast_cast_fu_858_p1;
        coeffs_5_load_cast_cast_reg_2314 <= coeffs_5_load_cast_cast_fu_854_p1;
        coeffs_6_load_cast_cast_reg_2309 <= coeffs_6_load_cast_cast_fu_850_p1;
        coeffs_7_load_cast_cast_reg_2304 <= coeffs_7_load_cast_cast_fu_846_p1;
        coeffs_8_load_cast_cast_reg_2299 <= coeffs_8_load_cast_cast_fu_842_p1;
        coeffs_9_load_cast_cast_reg_2294 <= coeffs_9_load_cast_cast_fu_838_p1;
        icmp_ln44_reg_2350 <= icmp_ln44_fu_1047_p2;
        out_word_last_reg_2364 <= out_word_last_fu_1070_p2;
        p_0_0_097_3039_load_reg_2344 <= p_0_0_097_3039_fu_318;
        sext_ln44_cast_reg_2179 <= sext_ln44_cast_fu_746_p1;
        x_reg_2354 <= x_fu_1062_p1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln44_fu_1047_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln44_reg_2350_pp0_iter28_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter29 == 1'b1))) begin
        ap_condition_exit_pp0_iter29_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter29_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter33_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) 
    & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1548_ce = 1'b1;
    end else begin
        grp_fu_1548_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1555_ce = 1'b1;
    end else begin
        grp_fu_1555_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1563_ce = 1'b1;
    end else begin
        grp_fu_1563_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1571_ce = 1'b1;
    end else begin
        grp_fu_1571_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1579_ce = 1'b1;
    end else begin
        grp_fu_1579_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1587_ce = 1'b1;
    end else begin
        grp_fu_1587_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1595_ce = 1'b1;
    end else begin
        grp_fu_1595_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1603_ce = 1'b1;
    end else begin
        grp_fu_1603_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1611_ce = 1'b1;
    end else begin
        grp_fu_1611_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1619_ce = 1'b1;
    end else begin
        grp_fu_1619_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1627_ce = 1'b1;
    end else begin
        grp_fu_1627_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1635_ce = 1'b1;
    end else begin
        grp_fu_1635_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1643_ce = 1'b1;
    end else begin
        grp_fu_1643_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1651_ce = 1'b1;
    end else begin
        grp_fu_1651_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1659_ce = 1'b1;
    end else begin
        grp_fu_1659_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1667_ce = 1'b1;
    end else begin
        grp_fu_1667_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1675_ce = 1'b1;
    end else begin
        grp_fu_1675_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1683_ce = 1'b1;
    end else begin
        grp_fu_1683_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1691_ce = 1'b1;
    end else begin
        grp_fu_1691_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1699_ce = 1'b1;
    end else begin
        grp_fu_1699_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1707_ce = 1'b1;
    end else begin
        grp_fu_1707_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1715_ce = 1'b1;
    end else begin
        grp_fu_1715_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1723_ce = 1'b1;
    end else begin
        grp_fu_1723_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1731_ce = 1'b1;
    end else begin
        grp_fu_1731_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1739_ce = 1'b1;
    end else begin
        grp_fu_1739_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1747_ce = 1'b1;
    end else begin
        grp_fu_1747_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1755_ce = 1'b1;
    end else begin
        grp_fu_1755_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1763_ce = 1'b1;
    end else begin
        grp_fu_1763_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1771_ce = 1'b1;
    end else begin
        grp_fu_1771_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1779_ce = 1'b1;
    end else begin
        grp_fu_1779_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1787_ce = 1'b1;
    end else begin
        grp_fu_1787_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln44_fu_1047_p2 == 1'd0))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln44_fu_1047_p2 == 1'd0))) begin
        in_stream_TREADY = 1'b1;
    end else begin
        in_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter34 == 1'b1))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter34 == 1'b1))) begin
        out_stream_TVALID = 1'b1;
    end else begin
        out_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_10_fu_1181_p1 = grp_fu_1579_p3;

assign acc_10_fu_1181_p3 = ((cmp31_5[0:0] == 1'b1) ? acc_10_fu_1181_p1 : acc_8_reg_2454);

assign acc_12_fu_1196_p1 = grp_fu_1587_p3;

assign acc_12_fu_1196_p3 = ((cmp31_6[0:0] == 1'b1) ? acc_12_fu_1196_p1 : acc_10_reg_2471);

assign acc_14_fu_1211_p1 = grp_fu_1595_p3;

assign acc_14_fu_1211_p3 = ((icmp7[0:0] == 1'b1) ? acc_14_fu_1211_p1 : acc_12_reg_2488);

assign acc_16_fu_1226_p1 = grp_fu_1603_p3;

assign acc_16_fu_1226_p3 = ((cmp31_8[0:0] == 1'b1) ? acc_16_fu_1226_p1 : acc_14_reg_2505);

assign acc_18_fu_1241_p1 = grp_fu_1611_p3;

assign acc_18_fu_1241_p3 = ((cmp31_9[0:0] == 1'b1) ? acc_18_fu_1241_p1 : acc_16_reg_2522);

assign acc_20_fu_1256_p1 = grp_fu_1619_p3;

assign acc_20_fu_1256_p3 = ((cmp31_10[0:0] == 1'b1) ? acc_20_fu_1256_p1 : acc_18_reg_2539);

assign acc_22_fu_1271_p1 = grp_fu_1627_p3;

assign acc_22_fu_1271_p3 = ((cmp31_11[0:0] == 1'b1) ? acc_22_fu_1271_p1 : acc_20_reg_2556);

assign acc_24_fu_1286_p1 = grp_fu_1635_p3;

assign acc_24_fu_1286_p3 = ((cmp31_12[0:0] == 1'b1) ? acc_24_fu_1286_p1 : acc_22_reg_2573);

assign acc_26_fu_1301_p1 = grp_fu_1643_p3;

assign acc_26_fu_1301_p3 = ((cmp31_13[0:0] == 1'b1) ? acc_26_fu_1301_p1 : acc_24_reg_2590);

assign acc_28_fu_1316_p1 = grp_fu_1651_p3;

assign acc_28_fu_1316_p3 = ((cmp31_14[0:0] == 1'b1) ? acc_28_fu_1316_p1 : acc_26_reg_2607);

assign acc_2_fu_1121_p3 = ((icmp[0:0] == 1'b1) ? grp_fu_1548_p3 : acc_reg_2375_pp0_iter3_reg);

assign acc_30_fu_1331_p1 = grp_fu_1659_p3;

assign acc_30_fu_1331_p3 = ((icmp10[0:0] == 1'b1) ? acc_30_fu_1331_p1 : acc_28_reg_2624);

assign acc_32_fu_1346_p1 = grp_fu_1667_p3;

assign acc_32_fu_1346_p3 = ((cmp31_16[0:0] == 1'b1) ? acc_32_fu_1346_p1 : acc_30_reg_2641);

assign acc_34_fu_1361_p1 = grp_fu_1675_p3;

assign acc_34_fu_1361_p3 = ((cmp31_17[0:0] == 1'b1) ? acc_34_fu_1361_p1 : acc_32_reg_2658);

assign acc_36_fu_1376_p1 = grp_fu_1683_p3;

assign acc_36_fu_1376_p3 = ((cmp31_18[0:0] == 1'b1) ? acc_36_fu_1376_p1 : acc_34_reg_2675);

assign acc_38_fu_1391_p1 = grp_fu_1691_p3;

assign acc_38_fu_1391_p3 = ((cmp31_19[0:0] == 1'b1) ? acc_38_fu_1391_p1 : acc_36_reg_2692);

assign acc_40_fu_1406_p1 = grp_fu_1699_p3;

assign acc_40_fu_1406_p3 = ((cmp31_20[0:0] == 1'b1) ? acc_40_fu_1406_p1 : acc_38_reg_2709);

assign acc_42_fu_1421_p1 = grp_fu_1707_p3;

assign acc_42_fu_1421_p3 = ((cmp31_21[0:0] == 1'b1) ? acc_42_fu_1421_p1 : acc_40_reg_2726);

assign acc_44_fu_1436_p1 = grp_fu_1715_p3;

assign acc_44_fu_1436_p3 = ((cmp31_22[0:0] == 1'b1) ? acc_44_fu_1436_p1 : acc_42_reg_2743);

assign acc_46_fu_1451_p1 = grp_fu_1723_p3;

assign acc_46_fu_1451_p3 = ((cmp31_23[0:0] == 1'b1) ? acc_46_fu_1451_p1 : acc_44_reg_2760);

assign acc_48_fu_1466_p1 = grp_fu_1731_p3;

assign acc_48_fu_1466_p3 = ((cmp31_24[0:0] == 1'b1) ? acc_48_fu_1466_p1 : acc_46_reg_2777);

assign acc_4_fu_1136_p1 = grp_fu_1555_p3;

assign acc_4_fu_1136_p3 = ((cmp31_2[0:0] == 1'b1) ? acc_4_fu_1136_p1 : acc_2_reg_2403);

assign acc_50_fu_1481_p1 = grp_fu_1739_p3;

assign acc_50_fu_1481_p3 = ((cmp31_25[0:0] == 1'b1) ? acc_50_fu_1481_p1 : acc_48_reg_2794);

assign acc_52_fu_1496_p1 = grp_fu_1747_p3;

assign acc_52_fu_1496_p3 = ((cmp31_26[0:0] == 1'b1) ? acc_52_fu_1496_p1 : acc_50_reg_2811);

assign acc_54_fu_1508_p1 = grp_fu_1755_p3;

assign acc_54_fu_1508_p3 = ((cmp31_27[0:0] == 1'b1) ? acc_54_fu_1508_p1 : acc_52_reg_2828);

assign acc_56_fu_1519_p1 = grp_fu_1763_p3;

assign acc_56_fu_1519_p3 = ((cmp31_28[0:0] == 1'b1) ? acc_56_fu_1519_p1 : acc_54_reg_2839);

assign acc_58_fu_1532_p1 = grp_fu_1771_p3;

assign acc_58_fu_1532_p3 = ((cmp31_29[0:0] == 1'b1) ? acc_58_fu_1532_p1 : acc_56_reg_2850);

assign acc_60_fu_1537_p1 = grp_fu_1779_p3;

assign acc_60_fu_1537_p3 = ((cmp31_30[0:0] == 1'b1) ? acc_60_fu_1537_p1 : acc_58_reg_2861);

assign acc_63_fu_1542_p1 = grp_fu_1787_p3;

assign acc_6_fu_1151_p1 = grp_fu_1563_p3;

assign acc_6_fu_1151_p3 = ((icmp4[0:0] == 1'b1) ? acc_6_fu_1151_p1 : acc_4_reg_2420);

assign acc_8_fu_1166_p1 = grp_fu_1571_p3;

assign acc_8_fu_1166_p3 = ((cmp31_4[0:0] == 1'b1) ? acc_8_fu_1166_p1 : acc_6_reg_2437);

assign acc_fu_1096_p1 = coeffs_0_load_cast_cast_reg_2339;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((1'b1 == ap_block_state35_pp0_stage0_iter34) & (ap_enable_reg_pp0_iter34 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter34 == 1'b1) & ((1'b1 == ap_block_state35_pp0_stage0_iter34) | (out_stream_TREADY == 1'b0))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter34 == 1'b1) & ((1'b1 == ap_block_state35_pp0_stage0_iter34) | (out_stream_TREADY == 1'b0))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((icmp_ln44_fu_1047_p2 == 1'd0) & (in_stream_TVALID == 1'b0));
end

always @ (*) begin
    ap_block_state35_pp0_stage0_iter34 = (out_stream_TREADY == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign coeffs_0_load_cast_cast_fu_874_p1 = $signed(coeffs_0_load_cast);

assign coeffs_10_load_cast_cast_fu_834_p1 = $signed(coeffs_10_load_cast);

assign coeffs_11_load_cast_cast_fu_830_p1 = $signed(coeffs_11_load_cast);

assign coeffs_12_load_cast_cast_fu_826_p1 = $signed(coeffs_12_load_cast);

assign coeffs_13_load_cast_cast_fu_822_p1 = $signed(coeffs_13_load_cast);

assign coeffs_14_load_cast_cast_fu_818_p1 = $signed(coeffs_14_load_cast);

assign coeffs_15_load_cast_cast_fu_814_p1 = $signed(coeffs_15_load_cast);

assign coeffs_16_load_cast_cast_fu_810_p1 = $signed(coeffs_16_load_cast);

assign coeffs_17_load_cast_cast_fu_806_p1 = $signed(coeffs_17_load_cast);

assign coeffs_18_load_cast_cast_fu_802_p1 = $signed(coeffs_18_load_cast);

assign coeffs_19_load_cast_cast_fu_798_p1 = $signed(coeffs_19_load_cast);

assign coeffs_1_load_cast_cast_fu_870_p1 = $signed(coeffs_1_load_cast);

assign coeffs_20_load_cast_cast_fu_794_p1 = $signed(coeffs_20_load_cast);

assign coeffs_21_load_cast_cast_fu_790_p1 = $signed(coeffs_21_load_cast);

assign coeffs_22_load_cast_cast_fu_786_p1 = $signed(coeffs_22_load_cast);

assign coeffs_23_load_cast_cast_fu_782_p1 = $signed(coeffs_23_load_cast);

assign coeffs_24_load_cast_cast_fu_778_p1 = $signed(coeffs_24_load_cast);

assign coeffs_25_load_cast_cast_fu_774_p1 = $signed(coeffs_25_load_cast);

assign coeffs_26_load_cast_cast_fu_770_p1 = $signed(coeffs_26_load_cast);

assign coeffs_27_load_cast_cast_fu_766_p1 = $signed(coeffs_27_load_cast);

assign coeffs_28_load_cast_cast_fu_762_p1 = $signed(coeffs_28_load_cast);

assign coeffs_29_load_cast_cast_fu_758_p1 = $signed(coeffs_29_load_cast);

assign coeffs_2_load_cast_cast_fu_866_p1 = $signed(coeffs_2_load_cast);

assign coeffs_30_load_cast_cast_fu_754_p1 = $signed(coeffs_30_load_cast);

assign coeffs_31_load_cast_cast_fu_750_p1 = $signed(coeffs_31_load_cast);

assign coeffs_3_load_cast_cast_fu_862_p1 = $signed(coeffs_3_load_cast);

assign coeffs_4_load_cast_cast_fu_858_p1 = $signed(coeffs_4_load_cast);

assign coeffs_5_load_cast_cast_fu_854_p1 = $signed(coeffs_5_load_cast);

assign coeffs_6_load_cast_cast_fu_850_p1 = $signed(coeffs_6_load_cast);

assign coeffs_7_load_cast_cast_fu_846_p1 = $signed(coeffs_7_load_cast);

assign coeffs_8_load_cast_cast_fu_842_p1 = $signed(coeffs_8_load_cast);

assign coeffs_9_load_cast_cast_fu_838_p1 = $signed(coeffs_9_load_cast);

assign grp_fu_1548_p1 = coeffs_1_load_cast_cast_reg_2334;

assign grp_fu_1555_p1 = coeffs_2_load_cast_cast_reg_2329;

assign grp_fu_1555_p2 = ((icmp[0:0] == 1'b1) ? grp_fu_1548_p3 : acc_reg_2375_pp0_iter3_reg);

assign grp_fu_1563_p1 = coeffs_3_load_cast_cast_reg_2324;

assign grp_fu_1563_p2 = ((cmp31_2[0:0] == 1'b1) ? acc_4_fu_1136_p1 : acc_2_reg_2403);

assign grp_fu_1571_p1 = coeffs_4_load_cast_cast_reg_2319;

assign grp_fu_1571_p2 = ((icmp4[0:0] == 1'b1) ? acc_6_fu_1151_p1 : acc_4_reg_2420);

assign grp_fu_1579_p1 = coeffs_5_load_cast_cast_reg_2314;

assign grp_fu_1579_p2 = ((cmp31_4[0:0] == 1'b1) ? acc_8_fu_1166_p1 : acc_6_reg_2437);

assign grp_fu_1587_p1 = coeffs_6_load_cast_cast_reg_2309;

assign grp_fu_1587_p2 = ((cmp31_5[0:0] == 1'b1) ? acc_10_fu_1181_p1 : acc_8_reg_2454);

assign grp_fu_1595_p1 = coeffs_7_load_cast_cast_reg_2304;

assign grp_fu_1595_p2 = ((cmp31_6[0:0] == 1'b1) ? acc_12_fu_1196_p1 : acc_10_reg_2471);

assign grp_fu_1603_p1 = coeffs_8_load_cast_cast_reg_2299;

assign grp_fu_1603_p2 = ((icmp7[0:0] == 1'b1) ? acc_14_fu_1211_p1 : acc_12_reg_2488);

assign grp_fu_1611_p1 = coeffs_9_load_cast_cast_reg_2294;

assign grp_fu_1611_p2 = ((cmp31_8[0:0] == 1'b1) ? acc_16_fu_1226_p1 : acc_14_reg_2505);

assign grp_fu_1619_p1 = coeffs_10_load_cast_cast_reg_2289;

assign grp_fu_1619_p2 = ((cmp31_9[0:0] == 1'b1) ? acc_18_fu_1241_p1 : acc_16_reg_2522);

assign grp_fu_1627_p1 = coeffs_11_load_cast_cast_reg_2284;

assign grp_fu_1627_p2 = ((cmp31_10[0:0] == 1'b1) ? acc_20_fu_1256_p1 : acc_18_reg_2539);

assign grp_fu_1635_p1 = coeffs_12_load_cast_cast_reg_2279;

assign grp_fu_1635_p2 = ((cmp31_11[0:0] == 1'b1) ? acc_22_fu_1271_p1 : acc_20_reg_2556);

assign grp_fu_1643_p1 = coeffs_13_load_cast_cast_reg_2274;

assign grp_fu_1643_p2 = ((cmp31_12[0:0] == 1'b1) ? acc_24_fu_1286_p1 : acc_22_reg_2573);

assign grp_fu_1651_p1 = coeffs_14_load_cast_cast_reg_2269;

assign grp_fu_1651_p2 = ((cmp31_13[0:0] == 1'b1) ? acc_26_fu_1301_p1 : acc_24_reg_2590);

assign grp_fu_1659_p1 = coeffs_15_load_cast_cast_reg_2264;

assign grp_fu_1659_p2 = ((cmp31_14[0:0] == 1'b1) ? acc_28_fu_1316_p1 : acc_26_reg_2607);

assign grp_fu_1667_p1 = coeffs_16_load_cast_cast_reg_2259;

assign grp_fu_1667_p2 = ((icmp10[0:0] == 1'b1) ? acc_30_fu_1331_p1 : acc_28_reg_2624);

assign grp_fu_1675_p1 = coeffs_17_load_cast_cast_reg_2254;

assign grp_fu_1675_p2 = ((cmp31_16[0:0] == 1'b1) ? acc_32_fu_1346_p1 : acc_30_reg_2641);

assign grp_fu_1683_p1 = coeffs_18_load_cast_cast_reg_2249;

assign grp_fu_1683_p2 = ((cmp31_17[0:0] == 1'b1) ? acc_34_fu_1361_p1 : acc_32_reg_2658);

assign grp_fu_1691_p1 = coeffs_19_load_cast_cast_reg_2244;

assign grp_fu_1691_p2 = ((cmp31_18[0:0] == 1'b1) ? acc_36_fu_1376_p1 : acc_34_reg_2675);

assign grp_fu_1699_p1 = coeffs_20_load_cast_cast_reg_2239;

assign grp_fu_1699_p2 = ((cmp31_19[0:0] == 1'b1) ? acc_38_fu_1391_p1 : acc_36_reg_2692);

assign grp_fu_1707_p1 = coeffs_21_load_cast_cast_reg_2234;

assign grp_fu_1707_p2 = ((cmp31_20[0:0] == 1'b1) ? acc_40_fu_1406_p1 : acc_38_reg_2709);

assign grp_fu_1715_p1 = coeffs_22_load_cast_cast_reg_2229;

assign grp_fu_1715_p2 = ((cmp31_21[0:0] == 1'b1) ? acc_42_fu_1421_p1 : acc_40_reg_2726);

assign grp_fu_1723_p1 = coeffs_23_load_cast_cast_reg_2224;

assign grp_fu_1723_p2 = ((cmp31_22[0:0] == 1'b1) ? acc_44_fu_1436_p1 : acc_42_reg_2743);

assign grp_fu_1731_p1 = coeffs_24_load_cast_cast_reg_2219;

assign grp_fu_1731_p2 = ((cmp31_23[0:0] == 1'b1) ? acc_46_fu_1451_p1 : acc_44_reg_2760);

assign grp_fu_1739_p1 = coeffs_25_load_cast_cast_reg_2214;

assign grp_fu_1739_p2 = ((cmp31_24[0:0] == 1'b1) ? acc_48_fu_1466_p1 : acc_46_reg_2777);

assign grp_fu_1747_p1 = coeffs_26_load_cast_cast_reg_2209;

assign grp_fu_1747_p2 = ((cmp31_25[0:0] == 1'b1) ? acc_50_fu_1481_p1 : acc_48_reg_2794);

assign grp_fu_1755_p1 = coeffs_27_load_cast_cast_reg_2204;

assign grp_fu_1755_p2 = ((cmp31_26[0:0] == 1'b1) ? acc_52_fu_1496_p1 : acc_50_reg_2811);

assign grp_fu_1763_p1 = coeffs_28_load_cast_cast_reg_2199;

assign grp_fu_1763_p2 = ((cmp31_27[0:0] == 1'b1) ? acc_54_fu_1508_p1 : acc_52_reg_2828);

assign grp_fu_1771_p1 = coeffs_29_load_cast_cast_reg_2194;

assign grp_fu_1771_p2 = ((cmp31_28[0:0] == 1'b1) ? acc_56_fu_1519_p1 : acc_54_reg_2839);

assign grp_fu_1779_p1 = coeffs_30_load_cast_cast_reg_2189;

assign grp_fu_1779_p2 = ((cmp31_29[0:0] == 1'b1) ? acc_58_fu_1532_p1 : acc_56_reg_2850);

assign grp_fu_1787_p1 = coeffs_31_load_cast_cast_reg_2184;

assign grp_fu_1787_p2 = ((cmp31_30[0:0] == 1'b1) ? acc_60_fu_1537_p1 : acc_58_reg_2861);

assign icmp_ln44_fu_1047_p2 = ((n_fu_198 == select_ln44_1) ? 1'b1 : 1'b0);

assign n_1_fu_1052_p2 = (n_fu_198 + 32'd1);

assign out_stream_TDATA = ((empty[0:0] == 1'b1) ? acc_63_fu_1542_p1 : acc_60_reg_2867);

assign out_stream_TKEEP = 4'd15;

assign out_stream_TLAST = out_word_last_reg_2364_pp0_iter33_reg;

assign out_stream_TSTRB = 4'd15;

assign out_word_last_fu_1070_p2 = ((n_fu_198 == sext_ln44_cast_reg_2179) ? 1'b1 : 1'b0);

assign sext_ln44_cast_fu_746_p1 = $signed(sext_ln44);

assign x_fu_1062_p1 = in_stream_TDATA[15:0];

endmodule //fir_filter_fir_filter_Pipeline_sample_loop
